### ISSUE TITLE
[Question] A way to see report from another pc on the network?

### ISSUE THREAD

**Issue by gprime31** [sensepost/gowitness#100]
Hi,
Is there a way to view the report from another pc on the local network?
it's 127.0.0.1:7171 when I run http://192.168.1.5:7171 it times out.

**Comment by gprime31** [comment]
also it's not my end because I run pythone3 webserver on port 7171 without the gowitness server running and i can view the screenshots.

**Comment by leonjza** [comment]
Check out my comment here https://github.com/sensepost/gowitness/issues/92#issuecomment-800988387. You can set it to `0.0.0.0` instead of `localhost` which will have the server listen on all interfaces.
