### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by fsacer** [sensepost/gowitness#101]
**Describe the bug**
Installation fails.

**To Reproduce**

```
go get github.com/sensepost/gowitness
# github.com/sensepost/gowitness/chrome
go/src/github.com/sensepost/gowitness/chrome/chrome.go:177:28: assignment mismatch: 4 variables but page.GetLayoutMetrics().Do returns 7 values
```

**Expected behavior**
gowitness would be in my gopath

**Version Information:**
- Parrot OS 4.11
```
go version
 go1.15.9 linux/amd64
```

**Comment by leonjza** [comment]
Thanks! I'll have a look today.

**Comment by sandexh** [comment]
Same issue , Following

**Comment by leonjza** [comment]
Should build fine after https://github.com/sensepost/gowitness/commit/d503334e569d5f7d0e471a65fe766c0cfb0fafee. Ill do a versioned release a bit later.
