### ISSUE TITLE
Import url list from metasploit

### ISSUE THREAD

**Issue by tigre-bleu** [sensepost/gowitness#105]
gowitness imports nmap xml file which is great. However, during an engagement, depending on the size of the network sometimes I prefer performing several smaller nmap scans then importing everything in Metasploit workspace as it is my main tool for big engagements. In that case gowitness is not so convenient due to the fact that there are multiple nmap xmls.

It would be nice if gowitness could interact with metasploit in some way to get the list of url to screnshot.

The most obvious (and probably easy) way to do it would be to export the workspace as a local file and to use that file as an input to gowitness. That would require to write a new parser.

Even beter was would be to write a MSF module but that would require quite a lot of additional work I guess.

**Comment by leonjza** [comment]
> The most obvious (and probably easy) way to do it would be to export the workspace as a local file and to use that file as an input to gowitness. That would require to write a new parser.

At the moment this will be the best way. Export to a file, massage it with some bash commands (`awk`/`sort`/`uniq` etc.) and use that as an input for the `file` subcommand with `-f` (or piped in via stdin). No need for a new parser.

As for MSF integration, I understand why this will be useful for some, but this is not something I would do anytime soon, and truthfully, I worry about too many parsers and the support burden that creates.

I'll leave this open for now to see if someone is up for taking a stab at it for now.

**Comment by leonjza** [comment]
Can reopen if someone wants to take a stab at it.
