### ISSUE TITLE
Some dialog boxes not ignored in target.go

### ISSUE THREAD

**Issue by danshearer** [sensepost/gowitness#106]
**Describe the bug**
Some sites have dialog boxes that are not ignored by the list of events in <code>target.go</code> .

**To Reproduce**

1. gowitness single "https://www.marinetraffic.com/"

2. screenshots/https-www.marinetraffic.com-.png contains a privacy popup with Accept/Agree across the bottom

**Expected behavior**

Popup ignored, as happens on many other sites.

**Screenshots**

![https-www marinetraffic com-](https://user-images.githubusercontent.com/3944577/120790092-62187380-c52a-11eb-9d0a-dd29ce1ea42f.png)

**Version Information:**
 - gowitness trunk
 - Ubuntu 21.04
 - Chromium 91.0.4472.77 snap

** Other Context **

I have read the [2019 update to why extensions don't work in headless mode](https://bugs.chromium.org/p/chromium/issues/detail?id=706008#c28) , because otherwise an extension like "I don't care about cookies" would do the trick.

I have tried "Accept All Cookies" in Settings in GUI mode.

**Comment by danshearer** [comment]
I am hoping the answer is not Selenium in non-headless mode, or Puppeteer. 

Gowitness is really well designed and implemented. You can even screenshot an entire CIDR!

**Comment by leonjza** [comment]
I realise this is not a JavaScript dialog box and will need some automation beyond that which gowitness supports. Right now I don't think this automation is the right thing to support yet. Sorry!
