### ISSUE TITLE
Feature Request prepend-https

### ISSUE THREAD

**Issue by 0xtavian** [sensepost/gowitness#11]
gowitness should have the option of prepending http/s like eyewitness does.

**Comment by leonjza** [comment]
Which sub command are you referring to? `scan` has the `--no-http` and `--no-https` flags as it prepends by default. `file` takes URLs from a file you provide so it didn't make sense to add it there and `single` is a URL you provide, so it also did not make sense to me there.

**Comment by 0xtavian** [comment]
Im referring to the sub command `file`. prepending http + https to every request is preferable when dealing with any list consisting of IP:PORT. Its easy to export IP:PORT from other tools but prepending http/s is essential when taking screen shots.

**Comment by leonjza** [comment]
Makes sense! At the moment the `file` sub command assumes URL's are provided. Will tag this as an enhancement. In the interim I guess one can generate a quick list with some bash one-liners.

**Comment by 0xtavian** [comment]
Yep! thats exactly what i did! Its just double the traffic!

**Comment by 0xtavian** [comment]
Right! With Eyewitness they have a `--prepend-htttps` that prepends http+https to every request so it makes it simple! Granted with Eyewitness you have to deal with 50%+ pages possibly being errors but IMO its worth it!!!

**Comment by 0xtavian** [comment]
Dont get me wrong, i love the way you guys deal with errors! so u might as well prepend http and https to every request!

**Comment by 0xtavian** [comment]
and then sort, like what was mentioned here https://github.com/sensepost/gowitness/issues/12
ok /end rant.

thanks guys!
