### ISSUE TITLE
Accept URLs as input file

### ISSUE THREAD

**Issue by cmprmsd** [sensepost/gowitness#111]
**Is your feature request related to a problem? Please describe.**
Reading Nmap-Files works great and is good for LAN environments.

Howver, when I test offsite servers often they share the same IP but have plenty of URLs and sub-URLs.
This is not possible currently and I think there might be an easy fix for that.

**Describe the solution you'd like**
Implement a file reader for a url list that will read lines as 
```
https://bla:9999
http://bla
http://test:2828
```

**Describe alternatives you've considered**
Currently I work around with the following command:
```bash
<urls xargs -P 4 -I HERE curl -X POST -F "url=HERE" http://localhost:7171/submit
```
However this does not give me precise error messages when e.g. there are URLs without procotol in the list.

**Additional context**
With reverse proxies you'll often find hundreds of subdomains or vhosts behind an IP and it'll be a good idea to discover them with gowitness.

PS: While the way I do it currently works, the perceptive sorting does not work any more. I don't know why this is. Maybe you do not do checksums of the images when the URL was added by the UI functionality?

Thanks in advance :)

**Comment by leonjza** [comment]
There is a `file` subcommand specifically for this. Check out `gowitness file --help` for more information.

**Comment by cmprmsd** [comment]
Wohoo thx @leonjza  :D 

I just jumped straight to the examples (https://github.com/sensepost/gowitness/wiki/Usage) and did not notice the other flags as only single, nmap and scan flags are mentioned.

The help within the commands is great. Thanks for the hint :)

**Comment by leonjza** [comment]
Yeah, that page needs some updates ;)
