### ISSUE TITLE
[FEATURE]add auth on web service

### ISSUE THREAD

**Issue by leveryd** [sensepost/gowitness#114]
**Is your feature request related to a problem? Please describe.**

`gowitness report serve` this web service has no auth.

**Describe the solution you'd like**

add some auth, even the simple "basic auth".

**Describe alternatives you've considered**

**Additional context**

**Comment by leonjza** [comment]
The report server ideally should only be run on your localhost. However, for cases where you may have wanted to run this elsewhere, I included a docker-compose example that leverages Traefik for an http basic auth layer in https://github.com/sensepost/gowitness/commit/2beb4adb0d81c7f01ffa00b9e79c501018fa73d5.
