### ISSUE TITLE
Unable to install gowitness on mac

### ISSUE THREAD

**Issue by anasizhar3** [sensepost/gowitness#119]
**Describe the bug**
I'm unable to install gowitness on mac using `go get -u github.com/sensepost/gowitness`. It is throwing me below errors:

```
~ go get -u github.com/sensepost/gowitness
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```
**To Reproduce**
Run below command on mac:
`go get -u github.com/sensepost/gowitness`

**Expected behavior**
As per installation guide, it should be installed with the command.

**Screenshots**
![image](https://user-images.githubusercontent.com/93522047/140859267-c8e92d6b-b3ee-4bed-8898-7f0bc3891c2c.png)

**Version Information:**
 - Mac OS
 - gowitness: 2.3.6

**Comment by leonjza** [comment]
I think this is just a warning for now (i'll update it sometime). Could you double check your `GOPATH`? I think it would have installed.

**Comment by aravindd007** [comment]
same problem please help me

**Comment by Curta7n** [comment]
install github.com/sensepost/gowitness@latest @aravindd007  @leonjza

**Comment by momosh1r0** [comment]
Hey guys 
I think is related to the go version you have installed, please check using:

`
go install github.com/sensepost/gowitness@latest
`
Remember to fix the plugin/exec_gowitness depending on the version you install.

**Comment by leonjza** [comment]
The [Installation](https://github.com/sensepost/gowitness/wiki/Installation) wiki document has the `go install` syntax.
