### ISSUE TITLE
Group similar pages like Aquatone did.

### ISSUE THREAD

**Issue by gprime31** [sensepost/gowitness#120]
add an option group similar pages like Aquatone did.

**Comment by leonjza** [comment]
As in perception sorting? The report server has this.

**Comment by gprime31** [comment]
no that kinda sux compaired to aquatone's.

**Comment by leonjza** [comment]
Feel free to open a PR with improvements.

**Comment by gprime31** [comment]
Don't get offended, I think gowitness is far better than aquatone overall , just that single aspect needs much improvement.

**Comment by leonjza** [comment]
No offense taken, just a legitimate request to help improve.

**Comment by leonjza** [comment]
Added hamming distance sorting for v3 now: https://github.com/sensepost/gowitness/commit/32dc9c74993d42252d61a63f43eea0e65a4848f5
