### ISSUE TITLE
HTTP/2 Support

### ISSUE THREAD

**Issue by randomactsofsecurity** [sensepost/gowitness#125]
**Describe the bug**
Certain websites require an automatic upgrade to HTTP/2

**To Reproduce**
Using an example website such as `www.aa.com` attempt to capture this screenshot from an AWS/VPC host / socks proxy to a AWS host (honestly not entirely sure what the root cause of this issue is). (Note, you'll need optional headers on this request as seen in the header PR)

![image](https://user-images.githubusercontent.com/51393999/151951900-4c08ad06-faaa-44e3-b4c2-2458d8951f4e.png)

However, building the project with the following transport settings w/ HTTP/2 in `chrome.go` [as referenced in this article.](https://jm33.me/make-http2-requests-via-proxy-in-golang.html)  

`"golang.org/x/net/http2"`

```
 err3 := http2.ConfigureTransport(transport)
	if err3 != nil {
		return
	}
```

![image](https://user-images.githubusercontent.com/51393999/151952436-5d1eb156-9773-4ac9-bfb3-e1d4c49d2201.png)

Might be useful to add this as an optional flag, or a fallback option if a first context-deadline is reached. It doesn't seem to break access to a lot of major websites... but of course on an internal network w/ old appliances I could see this being a problem. Will try to experiment as I run across assets that break with this config enabled.

**Expected behavior**
The preflight and screenshot request to succeed.

**Version Information:**
 - AWS Debian T2.medium

**Additional context**
Might be specific to network traffic originating from cloud resources, as I did not notice this behavior on my home network.

**Comment by randomactsofsecurity** [comment]
Actually, after doing some more testing, this is a valid issue, but I think adding any more improvements into the preflight (where a majority of the connections fail), is probably not worth the effort.

chromedp provides similar stubs for all the titles, response codes, status etc that gowitness is using to populate the db.  I ripped out the preflight checks from the code and chromedp finished in the 'same' amount of time.  Now, i haven't tried stubbing back in those same things yet to see if it significantly slows down chromedp.  But it may be worth it to get rid of preflight entirely, rather than trying to add all the headers/http2/etc that chromedp is already automatically doing by executing a browser session

**Comment by leonjza** [comment]
Removing the preflight logic is something I've wondered about a lot as well. If that information is obtainable from chromedp during a request then there really is no reason to have it anymore. The preflight logic came from the days when we still manually shelled out to spawn a chrome headless instance.

**Comment by randomactsofsecurity** [comment]
It's definitely quite a bit more annoying to pull the info (response body, headers) etc from chromedp which adds more complexity w/ listeners.  I wonder if there's a better HTTP library to use that would 'emulate' a browser better.

I'm also not sure where I can pull the TLS information from chromedp either, but its somewhere in the docs I'm sure

**Comment by leonjza** [comment]
In version 3, the preflight mechanic is removed. HTTP2 should be a non-issue now.
