### ISSUE TITLE
Disable taking screenshots by HTTP response code

### ISSUE THREAD

**Issue by retpoline** [sensepost/gowitness#133]
A list of hosts may return 404s and other status code nor worthy of creating a blank screenshot.

Can gowitness have a flag to ignore certain stat codes, such as 404 where there is no content to screenshot instead of filling up the screenshot folder with blank images?

Thanks for your time!

**Comment by leonjza** [comment]
I thought we had this already but realized we don't. This is definitely something simple to add! Thanks for the suggestion.

**Comment by nickspring** [comment]
I'll work on this.

**Comment by s0alqasim1d** [comment]
What happened to this?

I second #140 where you could specify codes to exclude instead of whitelisting just 200 OK as per the open PR. Or to be more flexible, there can be include and exclude. What do you think?

**Comment by leonjza** [comment]
Implemented [here](https://github.com/sensepost/gowitness/commit/1503c5b8b0285f25d03f4893ae2c92674451bacc), making it more versatile for more more than one response code.
