### ISSUE TITLE
How not to wait for the page to fully load

### ISSUE THREAD

**Issue by KaoriEl** [sensepost/gowitness#134]
Hi everyone, I'm having a problem loading pages. The page takes too long to load, although all the elements on it are loaded and you can interact with them, how can I not wait for the page to fully load, but just work further on the script?
I tried the methods from the previous questions on the git, but all those methods look very crutch, maybe there is already something else more elegant
Thank you.

**Comment by leonjza** [comment]
Got an example we can test with?
