### ISSUE TITLE
ERR failed to take screenshot error="exec: \"google-chrome\": executable file not found in $PATH"

### ISSUE THREAD

**Issue by molitona** [sensepost/gowitness#136]
Hi, I get ```
ERR failed to take screenshot error="exec: \"google-chrome\": executable file not found in $PATH"
``` whenever I run gowitness ??

**Comment by leonjza** [comment]
Is chrome installed and in your path?

**Comment by molitona** [comment]
no, should i install google chrome ?

**Comment by leonjza** [comment]
Yeah, and I just realized the [Installation](https://github.com/sensepost/gowitness/wiki/Installation) wiki page did not make that clear.

**Comment by molitona** [comment]
thanks would chromuim work ?

**Comment by molitona** [comment]
and please, isn't it multi threaded ?

**Comment by leonjza** [comment]
Chromium should work fine as we leverage [chromedp](https://github.com/chromedp/chromedp) to drive it. Gowitness uses goroutines for processing multiple URL's at the same time.

**Comment by molitona** [comment]
thanks, why ```gowitness single https://hackerone.com/ ``` fails ??
