### ISSUE TITLE
GET /screenshot API

### ISSUE THREAD

**Issue by khani3s** [sensepost/gowitness#139]
**Is your feature request related to a problem? Please describe.**
I would like to use the server to convert some embed and iframes charts to png. 
So I need a GET endpoint to point to my chart url and then It should return an PNG

**Describe the solution you'd like**
GET screenshot that process and return an image on the same request

**Describe alternatives you've considered**
Some workaround to convert the GET request to POST and then send to gowitness

**Comment by leonjza** [comment]
Tried this endpoint? https://github.com/sensepost/gowitness/wiki/API#take-a-screenshot
