### ISSUE TITLE
Feature Request: HTTP Title

### ISSUE THREAD

**Issue by Rhynorater** [sensepost/gowitness#14]
In future versions, would it be possible for the HTTP Title to be extracted when the GET response is parsed? That would be awesome.

Thanks,
Rhynorater

**Comment by leonjza** [comment]
Yeah this would be awesome! I have also been pondering about some light fingerprinting that could be done on the body we get from the initial connects.

**Comment by leonjza** [comment]
Added in https://github.com/sensepost/gowitness/commit/e01671b0e03500b2e66b757fb8d8a40f1530e842
