### ISSUE TITLE
Server report on custom directory

### ISSUE THREAD

**Issue by mpgn** [sensepost/gowitness#142]
**Is your feature request related to a problem? Please describe.**
I have a custom directory with all the screenshot but when I try to run the report feature, the custom directory is not taking in account and the screenshots directory is still used.

**Describe the solution you'd like**
`/gowitness-2.4.0-linux-amd64 -P vhost_screen server report`
The path to get all the screenshot should be on `vhost_screen` and not `/screenshots/`

```
└─$ ./gowitness-2.4.0-linux-amd64 -P vhost_screen server report  
07 Jul 2022 07:43:33 INF db path path=gowitness.sqlite3
07 Jul 2022 07:43:33 INF screenshot path path=vhost_screen
07 Jul 2022 07:43:33 INF server listening address=localhost:7171
[GIN] 2022/07/07 - 07:43:37 | 200 |   10.818721ms |       127.0.0.1 | GET      "/gallery"
[GIN] 2022/07/07 - 07:43:37 | 200 |    1.795967ms |       127.0.0.1 | GET      "/assets/css/tabler.min.css"
[GIN] 2022/07/07 - 07:43:37 | 200 |      84.265µs |       127.0.0.1 | GET      "/assets/js/tabler.min.js"
[GIN] 2022/07/07 - 07:43:37 | 404 |      27.143µs |       127.0.0.1 | GET      "/screenshots/http-10.0.0.1-80.png"
```

**Comment by leonjza** [comment]
I just tested this and realised the path you see in the logs is just the [HTTP path](https://github.com/sensepost/gowitness/blob/2.4.0/cmd/server.go#L107) according to the web server. The on disk path will be correctly set as `vhost_screen` as in your case, delivering the screenshots from there.

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/1148127/181919316-2336cbc2-1e2b-4272-b68d-7fde61e90013.png">
