### ISSUE TITLE
preflight request failed, despite site being up

### ISSUE THREAD

**Issue by ayushk58** [sensepost/gowitness#145]
Hi,
It's a question, I tried using gowitness for the first time in my recon process, and the input list was a bit massive, like 25k, when i checked the logs an hour later, I noticed that nearly 99% of the urls had a preflight request failed error, though the site had over few thousand working links and i had like 20-30 screenshots that too of 403 only.

Any idea what may be causing the error?

**Comment by leonjza** [comment]
Got some targets we can reproduce on?

**Comment by leonjza** [comment]
The preflight mechanic was removed in v3, so this should be much more reliable.
