### ISSUE TITLE
Docker Image seems to be broken? (assets 404)

### ISSUE THREAD

**Issue by 39ff** [sensepost/gowitness#153]
```
# docker run --rm -v $(pwd):/data -p7171:7171 leonjza/gowitness gowitness report serve --address :7171
10 Sep 2022 07:46:50 WRN this command is deprecated. use 'gowitness server' instead
10 Sep 2022 07:46:50 WRN exposing this server to other networks is dangerous! see the server command help for more information
10 Sep 2022 07:46:50 INF db path path=gowitness.sqlite3
10 Sep 2022 07:46:50 INF screenshot path path=screenshots
10 Sep 2022 07:46:50 INF server listening address=:7171
```

- Submit New URL -> https://example.com
- Access to Details Page.
- See the following images

![image1](https://user-images.githubusercontent.com/7544687/189474380-a58cb929-8dc1-4b65-bfa6-caaec3ff668f.PNG)
![image2](https://user-images.githubusercontent.com/7544687/189474388-58d5ec55-7b64-49ac-839c-65b911be0366.PNG)

```
Invalid : http://10.0.0.69:7171/details/assets/css/tabler.min.css
Valid: http://10.0.0.69:7171/assets/css/tabler.min.css
```

**Comment by leonjza** [comment]
Ah, this might be as a result of the last few PR's by @random-robbie to try and fix some pathing issues with a reverse proxy. I'll revert in a bit.

**Comment by leonjza** [comment]
More specifically, these: https://github.com/sensepost/gowitness/compare/73fe2252ca26c1571a16a513051572b0a951764d...ca2f86df54ef6ab3f691c744f346585c477061d7

**Comment by random-robbie** [comment]
Sorry about that! 

Certain parts work with the `./` on the main page but when its in /something/ it's messed up sorry!

I'll fork and test fully when I can to ensure it works both ways.

**Comment by leonjza** [comment]
I've reverted the PR's for now @39ff , give the Github Actions some time to rebuild the container. @random-robbie no worries! :) Would you mind elaborating a bit on what you are experiencing maybe that prompted those changes?

**Comment by random-robbie** [comment]
So while running nginx as the reverse proxy I was getting 404 for anything under assets as I have gowitness under a subfolder.

`Myserver.com/gowitness/`

But when loading the webserver I was getting 404 cause all the assets and links were going to 
`myserver.com/assets` instead of `myserver.com/gowitness/assets`

**Comment by leonjza** [comment]
Using a nginx configuration block such as the following with the new `--base-path` flag set to `/gowitness` should now have URL's correctly generated since https://github.com/sensepost/gowitness/commit/e904933ab1d877beca7f88b14b513144c5c23ca0.

```txt
server {
    listen       80;
    server_name  localhost;

...

    location /gowitness/ {
        proxy_pass          http://gowitness:7171/;
    }
}
```

**Comment by leonjza** [comment]
Wrote a slightly more verbose example here: https://github.com/sensepost/gowitness/wiki/Report-Server#on-reverse-proxies
