### ISSUE TITLE
too many SQL variables

### ISSUE THREAD

**Issue by r00tSe7en** [sensepost/gowitness#159]
2022/10/18 10:30:36 /root/go/pkg/mod/github.com/sensepost/gowitness@v0.0.0-20220911121411-c9c6b17993f2/cmd/merge.go:141 too many SQL variables

gowitness merge --input-path all/allweb_screenshots/tmp_sqlite3 -o all/allweb_screenshots/gowitness.sqlite3

**Comment by r00tSe7en** [comment]
Setting 100 has no effect. It may need to be optimized. If there is more data to be merged, it will fail

**Comment by leonjza** [comment]
I was able to replicate this in v3, and think it should be fixed now. Feel free to open a new issue if it still persists.
