### ISSUE TITLE
Broken Pages Navigator 

### ISSUE THREAD

**Issue by ikuamike** [sensepost/gowitness#160]
**Describe the bug**
The latest version of gowitness server has the pages navigator broken. When you have a lot of screenshots it only shows 1 page.

**To Reproduce**
1. Take a lot of screenshots possibly about 100 of them
2. Launch go witness server
3. Scroll to the bottom to view the pages navigator

**Expected behavior**
The expected behavior is to view the button to navigate the pages as in v2.4.1

**Screenshots**
The below is what is currently shown

![image](https://user-images.githubusercontent.com/5783614/196633053-2160e09f-5e73-4247-9068-aa2749512741.png)

Error from the command line, forgot to attach this. The below happens when I change pages via the URL since the UI doesn't 
 allow for this.
 
 http://localhost:7171/gallery?perception_sort=true&limit=66&page=1

![image](https://user-images.githubusercontent.com/5783614/196676537-1bf9206b-db93-4b15-8adc-737d770bf35d.png)

The below is the expected outcome that is in version 2.4.1

![image](https://user-images.githubusercontent.com/5783614/196633323-5ea739ab-71ac-483b-b36f-09f3a86b349e.png)

**Version Information:**
  - gowitness: 2.4.2

**Comment by leonjza** [comment]
Sorry, this is not enough information to debug. Some ideas to check:
- Any errors in the browser console or the terminal you are launching the server from?
- Is the correct database being used?

**Comment by ikuamike** [comment]
I've updated the issue with the command line error

**Comment by leonjza** [comment]
v3 UI is completely rewritten. Feel free to open issues for that instead if its still doing this.
