### ISSUE TITLE
Taking screenshots of HTTPS pages that require a browser exeption

### ISSUE THREAD

**Issue by brooky75** [sensepost/gowitness#162]
Hello,
Is there a way to use Gowitness to take screenshots of HTTPS pages that require confimation of the exeption before arriving at the landing page?

**Comment by leonjza** [comment]
Old issue, but feel free to re-open it with more information. Can you show a sample of what you'd like to do? You can pass in custom JavaScript to drive some interaction if that is what you want using the `--javascript` flag in v3 (check `scan --help` for details).
