### ISSUE TITLE
21 Nov 2022 14:24:03 INF processing complete - But no screenshot were captured

### ISSUE THREAD

**Issue by agrawalsmart7** [sensepost/gowitness#164]
Hey there,

I have a list of 500 urls, and I wanted to capture the screenshot so I run this command-

`gowitness.exe file -f .\working_500.txt --threads 20`

But after hitting the enter I am getting the process complete but when I check the screenshots folder none image was found. And also I can see the sql3 file was there.

What should I do here?

**Comment by leonjza** [comment]
Need more information to help. gowitness prints a lot of logs and is probably telling you if something went wrong.

Regardless, v3 is about to release with some major changes. Test it and if you're still struggling, feel free to open a new issue.
