### ISSUE TITLE
Ports options for "file" command

### ISSUE THREAD

**Issue by h49nakxs** [sensepost/gowitness#165]
Hi there,

Would it be possible to add to the "file" command the same ports options that exist for the "scan" command ?
I mean the following ones :

--ports string
--ports-large
--ports-medium
--ports-small

That would avoid some extra bash gymnastic to add the custom ports to the URLs file.

By the way, great tool, thanks !

**Comment by stephenbond** [comment]
Agree, came here to ask the same thing...

**Comment by leonjza** [comment]
Added in v3.
