### ISSUE TITLE
Request: Allow perception sort in static export

### ISSUE THREAD

**Issue by initstring** [sensepost/gowitness#167]
**Is your feature request related to a problem? Please describe.**

We use the static HTML export function as we host weekly reports on our own web server. This works well, but we have a lot of identical-looking screenshots across different targets and it would be really nice if we could do perception sorting.

**Describe the solution you'd like**

Add a flag that enables perception sort on the static HTML export option. Example:

`gowitness report export -f report.zip -perception-sort`

I believe this may have existed in older versions.

**Describe alternatives you've considered**

N/A

**Additional context**

Thank you so much for the time and effort you put into building and maintaining this tool!

**Comment by initstring** [comment]
> * The ability to click "Visit URL" for screenshots

I've submitted a very small PR here to simply make URLs clickable in static exports: https://github.com/sensepost/gowitness/pull/172

**Comment by leonjza** [comment]
I added this to the static exports in this commit: https://github.com/sensepost/gowitness/commit/32dc9c74993d42252d61a63f43eea0e65a4848f5
