### ISSUE TITLE
Database Merge Issues

### ISSUE THREAD

**Issue by Syrkadian** [sensepost/gowitness#173]
**Describe the bug**
Data inconsistencies occur when merging database files.  The Network, Console, and Technologies category counts do not match when comparing database files before and after merging. 

**To Reproduce**
1. Check category counts in respective databases
2. Merge databases
3. Reconcile category counts of the pre-merge databases and the output of the merge
4. Observe discrepancies

**Expected behavior**
The output of a merge would contain accurate category counts that were present in the databases before a merge. 

**Screenshots**
![image](https://user-images.githubusercontent.com/39872088/213287348-72899e90-2d06-4326-9ddc-5b91005e1363.png)

![image](https://user-images.githubusercontent.com/39872088/213287459-41282681-aed2-4ec8-9f58-bf6b7109c912.png)

**Version Information:**
 - OS: Debian GNU/Linux 11
 - gowitness: gowitness: 2.4.2

**Additional context**
Please see the attached tar file for copies of the pre-merge databases and the post-merge result.
[dbs.tar.gz](https://github.com/sensepost/gowitness/files/10450918/dbs.tar.gz)

**Comment by leonjza** [comment]
Merging was rewritten in v3. If the issue still persists, feel free to reopen another issue.
