### ISSUE TITLE
[Feature Request] Export as JPEG 

### ISSUE THREAD

**Issue by xhzeem** [sensepost/gowitness#175]
**Is your feature request related to a problem? Please describe.**
PNG files are larger in size than JPEG, it's better to support JPEG as it will take less space on disk, especially when the project is big

Right now only PNG and PDF formats are available, adding JPEG will be great.

**Comment by MisconceivedSec** [comment]
Agreed :arrow_up:

**Comment by leonjza** [comment]
Added in v3 via the `--screenshot-format` flag.
