### ISSUE TITLE
Ability to Supply Host + Subdirectories

### ISSUE THREAD

**Issue by caelin-kail** [sensepost/gowitness#176]
Not sure if this is currently possible but when testing, it doesn't seem like I can supply gowitness with a URL that contains a subdirectory. 

Example: 
Providing a URL of https://stackoverflow.com/questions instead of just https://stackoverflow.com

**Comment by leonjza** [comment]
Closing due to age, but I'm also not sure about this one. Can you show an example? Feel free to reopen if there is information on a bug. Ideally, test v3 ;)
