### ISSUE TITLE
excute javascript code in the dom of chromuim 

### ISSUE THREAD

**Issue by djallalzoldik** [sensepost/gowitness#179]
### Example:

![javascript](https://user-images.githubusercontent.com/45321671/222837669-e0865e58-4f39-44f6-8066-fe834d993402.png)

### Result

![gowitness2024](https://user-images.githubusercontent.com/45321671/222837957-6dc6ea6f-0c86-4445-ad29-ff63fcbd4a99.png)

**Comment by leonjza** [comment]
Landed in #180
