### ISSUE TITLE
Can't make screenshot of very slow websites

### ISSUE THREAD

**Issue by AskanSimon** [sensepost/gowitness#18]
Hello,

I made a few test, but this chinese websites don't work

```
./gowitness single --chrome-timeout 100 -u http://www.quippbattery.com/Home.aspx 
ERRO[2019-02-24 15:55:32] Failed to query url                           error="[Get http://www.quippbattery.com/Home.aspx: read tcp 192.168.178.41:35752->222.76.212.44:80: i/o timeout]" url="http://www.quippbattery.com/Home.aspx"
INFO[2019-02-24 15:55:32] Complete                                      run-time=5.266110312s
```

I think the "Failed to query url" Error comes to early. " --chrome-timeout 100" has no effect.

Thank you, Best Regards
Simon

**Comment by leonjza** [comment]
The `--chrome-timeout` flag sets the timeout for chrome itself. Try and add the `--timeout` to affect the initial HTTP connections timeout.

**Comment by AskanSimon** [comment]
thank you. `--timeout` solves the problem!
