### ISSUE TITLE
Sytanx error line 8

### ISSUE THREAD

**Issue by Warren3013** [sensepost/gowitness#181]
**Describe the bug**
When trying to run gowitness I get the below error.
![image](https://user-images.githubusercontent.com/53001575/226153656-dc934fd1-8b6b-435f-ab30-9ed412e2e6ae.png)

**To Reproduce**
1. run gowitness single --help
2. see error
3. 
![image](https://user-images.githubusercontent.com/53001575/226153667-2b1beb06-ae51-475a-b8d6-0a45528a5aa0.png)

**Expected behavior**
display flags for tool usage

**Screenshots**
![image](https://user-images.githubusercontent.com/53001575/226153667-2b1beb06-ae51-475a-b8d6-0a45528a5aa0.png)

**Version Information:**
 - Kali VM 2023.1
 - gowitness: 2.4.2
**Additional context**

**Comment by leonjza** [comment]
How did you install gowitness?

**Comment by Warren3013** [comment]
Hi

I installed go witness through the go command on the github wiki install.

Kind regards
Warren

**Comment by leonjza** [comment]
In a fresh Kali VM, after installing `golang` via apt, installing gowitness with `go install github.com/sensepost/gowitness@latest` and fixing up my `PATH` to include `~/go/bin`, it works works fine for me.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/1148127/226160845-9069df18-2053-4790-ab8f-ce7379db8a1f.png">

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/1148127/226160882-f5d96179-7732-4d62-80b1-61631b162886.png">

**Comment by Warren3013** [comment]
Thank you will try that.

Kind regards
Warren
