### ISSUE TITLE
Issue merging databases

### ISSUE THREAD

**Issue by skilfoy** [sensepost/gowitness#186]
**Describe the bug**

Databases won't merge. I'm using Kali Linux 2023.1, already performed sudo apt update.
```
└─$ ls -al ../dbs          
total 19396
drwxr-xr-x 2 kali kali    4096 May 22 10:55 .
drwxr-xr-x 5 kali kali    4096 May 22 10:56 ..
-rw-r--r-- 1 kali kali 3297280 May 19 11:26 gw1.sqlite3
-rw-r--r-- 1 kali kali 3227648 May 22 10:54 gw2.sqlite3
-rw-r--r-- 1 kali kali 6868992 May 22 10:54 gw3.sqlite
-rw-r--r-- 1 kali kali 6459392 May 22 10:55 gw4.sqlite3
```
```
└─$ gowitness merge --input-path ../dbs 
22 May 2023 11:17:29 INF number of dbs to process database-count=4
22 May 2023 11:17:29 FTL could not open destination db error="unsupported database URI provided" destination=gowitness-merged.sqlite3
```

I've also tried specifying each database using the `-i` flag and/or specifying `-o` for the output database. I've started a new gowitness server and tried re-running the merge command. All result in the same error:
`FTL could not open destination db error="unsupported database URI provided" destination=gowitness-merged.sqlite3`

**To Reproduce**
- See notes above.

**Expected behavior**
I expect the databases to merge as indicated in the help file.

**Comment by leonjza** [comment]
I've rewritten database merging in v3, feel free to test it out and report issues.
