### ISSUE TITLE
Full Size Screenshots

### ISSUE THREAD

**Issue by AskanSimon** [sensepost/gowitness#19]
Hello,

I try include the "--fullPage" flag for chrome, instead of resolution. But with no success.
This is very useful when you have pages with different lengths. Long product lists etc.

I would be very grateful for any help.

Best Regards
Askan

**Comment by leonjza** [comment]
I can't seem to find the cli flag for this. Could you point me to some documentation perhaps?

**Comment by austinginder** [comment]
I think you need to trick headless Chrome to pull this off. See this example: https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a. They are basically measuring the full height of the rendered page then adjusting Emulation.setVisibleSize accordingly.

**Comment by leonjza** [comment]
V2 is getting it! 🎉

**Comment by thanh-manci** [comment]
@leonjza its should be --fullpage not --fullPage

**Comment by leonjza** [comment]
> @leonjza its should be --fullpage not --fullPage

What do you mean? https://github.com/sensepost/gowitness/commit/6cb4915d29fc047f6f9bfde5ef2fe665302188a3#diff-ab967ab1a2f3a1b769106eeb7bfe892ef0e81d1d27811fa15be08e6749feee1fR67

**Comment by thanh-manci** [comment]
@austinginder 
@leonjza 
@AskanSimon 
@marcpeiser 
Hello! 
how to use fullpage with report server?
what's the name of parameter?
let's show me. very thank!

**Comment by leonjza** [comment]
The report server does not support this yet. It is only a CLI option.

**Comment by thanh-manci** [comment]
@leonjza 
so the only thing I can do is build a server in conjunction with cli.
have any way to do that?

**Comment by thanh-manci** [comment]
I saw in cmd/root.go:66
rootCmd.PersistentFlags().BoolVarP(&chrm.FullPage, "fullpage", "F", false, "take fullpage screenshots")
I just set true in that. its working.
