### ISSUE TITLE
Docker images fail with GLIBC error

### ISSUE THREAD

**Issue by theRealFr13nd** [sensepost/gowitness#194]
**Describe the bug**
I think the docker containers contain gowitness versions that is linked again a LIBC that is missing from the container. When attempting to run the containers a GLIBC error is returned.

**To Reproduce**
1. Clone the docker container from either `ghcr.io/sensepost/gowitness:latest` or `docker pull leonjza/gowitness`.
2. Run the container with the command `docker run ghcr.io/sensepost/gowitness gowitness` or `docker run leonjza/gowitness gowitness`
3. Error is displayed

**Expected behavior**
Gowitness to execute without any errors.

**Screenshots**
![image](https://github.com/sensepost/gowitness/assets/36172640/290ac20e-4679-47bc-9084-b1872a592bfa)

**Version Information:**
![image](https://github.com/sensepost/gowitness/assets/36172640/679861cf-861f-452c-a3cc-7f4f29dc7d11)

**Additional context**

**Comment by leonjza** [comment]
Thanks for reporting this. Images with the `latest` tag should be fixed after the CI [completes](https://github.com/sensepost/gowitness/actions/runs/5653298713/job/15314257244).

**Comment by theRealFr13nd** [comment]
Thanks!!!
