### ISSUE TITLE
Dashboard navigation pages don't wrap

### ISSUE THREAD

**Issue by dmuhs** [sensepost/gowitness#195]
**Describe the bug**

When doing recon on a large amount of assets, the number of pages on the dashboard can exceed ~70, after which the page numbers continue to the right.

**To Reproduce**
1. Ingest a large number of URLs (my current database has 13273)
2. Go to the dashboard hosted by `gowitness server`
3. The page number list at the bottom of the site overflows very far to the right

**Expected behavior**

The page numbers should wrap in their bounding box and continue at the bottom. Even better, not all page numbers have to be shown. 10 pages before and 10 pages after the current one will suffice.

**Screenshots**

**Version Information:**

Built today from the latest dev branch:

```
gowitness: 2.5.0

git hash: dev
go version: dev
```

**Additional context**

Thank you so much for this great tool! I really appreciate the work. It's saving me an absurd amount of hours of manual analysis!

**Comment by leonjza** [comment]
I rewrote the UI for v3, feel free to test it out and let me know!
