### ISSUE TITLE
Possible to scan multiple CIDR ranges at once?

### ISSUE THREAD

**Issue by naterobbified** [sensepost/gowitness#2]
First off, great tool. Is there a way to scan multiple CIDR ranges at once? I tried separating by commas and spaces but seems to be a no go. I guess I can just write up a quick for loop... Thanks again.

**Comment by leonjza** [comment]
Hey!

This is not possible yet, but definitely an easy addition. I'll get to it asap!

**Comment by leonjza** [comment]
Added this and tagged with v1.0.2
