### ISSUE TITLE
Exclude port(s) from being accessed

### ISSUE THREAD

**Issue by pinetest** [sensepost/gowitness#207]
**Is your feature request related to a problem? Please describe.**
When scanning hosts on an internal subnet, often based on a nmap xml file, there could be printers with open ports. Port 1900 on printers allow for direct printing of the data that is sent. When gowitness is started with nmap & --open it will also try to access port 1900 causing the printer to print out the HTTP requests.

**Describe the solution you'd like**
An option, for example "--exclude-ports", to prevent certain ports to be accessed by the scanner.

**Comment by leonjza** [comment]
Added in v3.
