### ISSUE TITLE
[FEATURE REQUEST] Add ability to specify CDP websocket for a remote chrome instance

### ISSUE THREAD

**Issue by deoxykev** [sensepost/gowitness#210]
**Is your feature request related to a problem? Please describe.**
- I would like to use a remote chrome browser. My endpoint exposes the devtools via websocket, as standard practice for headless chrome. This makes it possible to use many 3rd party tools such as browserless.io.

**Describe the solution you'd like**
- Via environment variable and CLI flag, you should be able to specify the websocket URL. 

**Describe alternatives you've considered**
- Proxy the entire machine (bad opsec)

**Additional context**
- Here is an example of how to specify a websocket URL: https://github.com/chromedp/examples/blob/master/remote/main.go#L21
- The line to replace would be here: https://github.com/sensepost/gowitness/blob/master/chrome/chrome.go#L268

---

I think something like this could work in [chrome/chrome.go](https://github.com/sensepost/gowitness/blob/master/chrome/chrome.go#L268), but i'm not entirely familiar with the codebase. Can you doublecheck?

```go
	var actx chromedp.Context
	var acancel context.CancelFunc
	var devtoolsWsURL *string

	// Check if REMOTE_DEVTOOLS_WS_URL environment variable is set
	if wsURL := os.Getenv("REMOTE_DEVTOOLS_WS_URL"); wsURL != "" {
		devtoolsWsURL = &wsURL
		actx, acancel = chromedp.NewRemoteAllocator(context.Background(), *devtoolsWsURL)
	} else {
		actx, acancel = chromedp.NewExecAllocator(context.Background(), chromedp.DefaultExecAllocatorOptions...)
	}

	// Use actx and acancel here
	defer acancel()
```

**Comment by leonjza** [comment]
Added with the `--chrome-wss-url` flag in v3.
