### ISSUE TITLE
Getting error while taking screenshot

### ISSUE THREAD

**Issue by moolakarapaiyan** [sensepost/gowitness#213]
Gowitness works well. 
Today, I cleaned up the /tmp folder on my Ubuntu machine, and after that, it started giving me errors while taking screenshots

i gave read write permission to /tmp folder

23 Jan 2024 05:12:42 DBG ../../go/pkg/mod/github.com/sensepost/gowitness@v0.0.0-20231219153055-042af5cadcd5/cmd/root.go:35 > debug logging enabed
23 Jan 2024 05:12:42 DBG ../../go/pkg/mod/github.com/sensepost/gowitness@v0.0.0-20231219153055-042af5cadcd5/lib/processor.go:121 > preflighting url=https://example.com/
23 Jan 2024 05:12:43 INF ../../go/pkg/mod/github.com/sensepost/gowitness@v0.0.0-20231219153055-042af5cadcd5/lib/processor.go:135 > preflight result statuscode=200 title="Example Domain" url=https://example.com/
23 Jan 2024 05:12:43 DBG ../../go/pkg/mod/github.com/sensepost/gowitness@v0.0.0-20231219153055-042af5cadcd5/lib/processor.go:157 > screenshotting url=https://example.com/
23 Jan 2024 05:12:43 ERR ../../go/pkg/mod/github.com/sensepost/gowitness@v0.0.0-20231219153055-042af5cadcd5/lib/processor.go:67 > failed to take screenshot error="chrome failed to start:\n[0123/051243.926698:ERROR:command_line_handler.cc(137)] Could not create directory /tmp/chromedp-runner3496925935: No such file or directory (2)\n"
23 Jan 2024 05:12:43 DBG ../../go/pkg/mod/github.com/sensepost/gowitness@v0.0.0-20231219153055-042af5cadcd5/cmd/single.go:58 > failed to witness url error="chrome failed to start:\n[0123/051243.926698:ERROR:command_line_handler.cc(137)] Could not create directory /tmp/chromedp-runner3496925935: No such file or directory (2)\n" url=https://example.com/

**Comment by BCHarrell** [comment]
Running into the same error, but I hadn't cleaned out /tmp - fresh install. Did you figure this out?

**Comment by leonjza** [comment]
Not sure why to be honest. That said, Chrome instances launched in v3 will isolate its user directory and try clean up after itself now.
