### ISSUE TITLE
In standalone mode, can multiple instances of screenshotting be done in parallel?

### ISSUE THREAD

**Issue by ismyhc** [sensepost/gowitness#214]
Id like to use gowitness as a standalone library.

Can I take screenshots of multiple url's in parallel? Or would I need to do it sequentially?

**Comment by leonjza** [comment]
For v3 I plan on restructuring the project layout to be more friendly to use as a library. That said you can take screenshots in parallel using goroutines. An example of how its done in gowitness today is [here](https://github.com/sensepost/gowitness/blob/2.5.1/cmd/file.go#L60).

**Comment by ismyhc** [comment]
> For v3 I plan on restructuring the project layout to be more friendly to use as a library. That said you can take screenshots in parallel using goroutines. An example of how its done in gowitness today is [here](https://github.com/sensepost/gowitness/blob/2.5.1/cmd/file.go#L60).

Awesome. Will take a look. 🙏
