### ISSUE TITLE
executable file not found in $PATH

### ISSUE THREAD

**Issue by prasgop** [sensepost/gowitness#215]
I am getting the below error when trying to run gowitness in kali-

gowitness single http://www.google.com
10 Mar 2024 01:28:11 INF preflight result statuscode=200 title=Google url=http://www.google.com
10 Mar 2024 01:28:11 ERR failed to take screenshot error="exec: \"google-chrome\": executable file not found in $PATH"

Can someone please tell me how to fix it? I am a beginner 

Thanks

**Comment by nobodynate** [comment]
I had the same issue on kali in WSL while using the precompiled binary. The issue is that gowitness cannot find the chrome binary in the expected location, so either put it in the expected location or tell gowitness where to find it by using the `--chrome-path` option.

My WSL solution is like:
```
gowitness <other args> --chrome-path /mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe
```
