### ISSUE TITLE
single url error

### ISSUE THREAD

**Issue by Sh4d0wx0x5F** [sensepost/gowitness#221]
**Describe the bug**
Can't get iimage of the provided url

**To Reproduce**
1. Go to 'https://twitter.com'

**Expected behavior**
![Screenshot 2024-06-19 045219](https://github.com/sensepost/gowitness/assets/97059953/bb078b2a-411b-4581-8fdb-15fcadb1cb3a)

**Screenshots**

**Version Information:**
 - gowitness: [e.g. 1.3.3]

**Additional context**

**Comment by leonjza** [comment]
The preflighter was removed in v3 which should resolve this. Feel free to test it out when its released soon!
