### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rix4uni** [sensepost/gowitness#222]
urls.txt file contains:
https://www.avg.com/en-au/download-thank-you.php?product=VPI
https://www.avg.com/en-us/download-thank-you.php?product=SBR-ANDROID

![image](https://github.com/sensepost/gowitness/assets/72344025/bf23e290-3329-4a81-8f27-439e3286ca52)

**Comment by rix4uni** [comment]
In go.md i change this line `github.com/projectdiscovery/wappalyzergo v0.1.6` in to `github.com/projectdiscovery/wappalyzergo v0.1.8` now it's working. and run this command

rm -rf go.sum && go mod tidy

**Comment by leonjza** [comment]
Thanks for debugging this, I'll bump dependencies shortly!

**Comment by leonjza** [comment]
Hopefully fixed in https://github.com/sensepost/gowitness/commit/4c2960b33a15bc6caa4d9d7a20cea36d8c0028e4.
