### ISSUE TITLE
Go install broken due to missing ui/dist directory

### ISSUE THREAD

**Issue by defektive** [sensepost/gowitness#230]
**Describe the bug**
We can no longer perform a simple go install as documented here: https://github.com/sensepost/gowitness/wiki/Installation

```bash
go install github.com/sensepost/gowitness@latest
```

This fails with the following error message:
```txt
github.com/sensepost/gowitness@v0.0.0-20240917135917-fc06051f78e6/web/spa.go:13:12: pattern ui/dist/*: no matching files found
```

**To Reproduce**
1. Open a terminal
2. run `go install github.com/sensepost/gowitness@latest`
3. See error

**Expected behavior**

**Version Information:**
 - OS: Linux
 - gowitness: @latest

**Additional context**
Not sure how you want to approach this. Since fixing it will probably require committing compiled assets. maybe the real answer is no more `go install github.com/sensepost/gowitness@latest` and build via makefile or download a release.

**Comment by leonjza** [comment]
You're a bit fast for me 😊 I just merged the v3 branch and am ironing out the last few issues before tagging a release.

**Comment by leonjza** [comment]
Should be fine now.
