### ISSUE TITLE
Immediate mode missing in v3

### ISSUE THREAD

**Issue by j1cs** [sensepost/gowitness#231]
**Describe the bug**
I was using your project to take screenshot with mobile size using the api.
now with your recent version seems now is different.

**To Reproduce**
My docker compose before your update was:
```
  gowitness:
    image: ghcr.io/sensepost/gowitness:latest
    command: gowitness server --address 0.0.0.0:7171 -X 769 -Y 1024
```
which now shows:
```
  The error was:

  unknown command "server" for "gowitness"
```
I just tried your new version like:
```
  gowitness:
    image: ghcr.io/sensepost/gowitness:latest
    command: gowitness report server  -X 769 -Y 1024
```
which shows the usage page and doesn't recognize -X and -Y flags.

**Expected behavior**
now i wonder how do i set up -X and -Y? can you show me an example or update your documentation to see if this still fit with my requirements

**Version Information:**
 - OS: Archlinux with docker
 - gowitness: lastest

**Additional context**
As i said before i was using your project only to take screenshots with a custom size and send it on the fly to my system using the `/screenshot` endpoint behind nginx with basic auth 
using resty like:
```

func (c *RestClient) PostScreenshot(ctx context.Context, url string, pathFile string) (int, []byte, error) {
	body := map[string]string{
		"url":     url,
		"oneshot": "true",
	}
	response, err := c.R().
		SetBasicAuth(os.Getenv("SCREEN_USER"), os.Getenv("SCREEN_PASSWORD")).
		SetContext(ctx).
		SetHeaders(headers).
		SetBody(body).
		SetOutput(pathFile).
		Post(constant.ScreenshotURLApi)
	return response.StatusCode(), response.Body(), err

}
```

I don't know if i can achieve that now with your refactor.
Also i can't go back and use your previous version using docker since ain't versioned like:
```
  gowitness:
    image: ghcr.io/sensepost/gowitness:2.5.1 # <----- previous version
    command: gowitness server --address 0.0.0.0:7171 -X 769 -Y 1024
```
docker says `manifest unknown`

**Comment by leonjza** [comment]
You're a bit fast for me 😊 I just merged the v3 branch and am ironing out the last few issues before tagging a release. There is some swagger documentation for a much better api (which lets you specify x and y in the call) that is available once the server is up at `/swagger/`.

Ill have updated docs, and a huge release post coming.

**Comment by leonjza** [comment]
Having booted the reporting / api server on your local host, check out: http://localhost:7171/swagger/index.html

**Comment by leonjza** [comment]
<img width="728" alt="image" src="https://github.com/user-attachments/assets/c58b3e75-9771-4303-be2b-049ddbaf9460">

**Comment by j1cs** [comment]
The problem with this is now i can't get the actual file. Now response `"Probing started"` and before i could get the file in bytes as i showed you in my previous example.

**Comment by leonjza** [comment]
Ah right, sorry I missed that part. Yeah an immediate mode is missing; I'll add it back!

**Comment by leonjza** [comment]
Added here. https://github.com/sensepost/gowitness/commit/c4478e2db7a2e8628710678afafe5754e29a2138

It's a bit different to the old API where the raw screenshot came back IIRC. You now get json back with all of the collected information which also includes the screenshot.

Here is an example to extract the raw screenshot:

```text
$ curl -s -X POST \
  http://localhost:7171/api/submit/single \
  -H "Content-Type: application/json" \
  -d '{"url": "https://sensepost.com"}' | \
    jq -r .screenshot | base64 -D | file -

/dev/stdin: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 3840x1882, components 3
```
