### ISSUE TITLE
screenshot of ips with ports predefined

### ISSUE THREAD

**Issue by jaikishantulswani** [sensepost/gowitness#232]
**Describe the bug**
Hi @leonjza This current new version of gowitness is not taking screenshot of ips provided from file which are having ports included like
example.com:25
127.0.0.1:8552

As it is now taking screenshot on default ports only 443,80

**Comment by leonjza** [comment]
Ah thanks. I'll fix this.

**Comment by leonjza** [comment]
Try again and let me know! Should also support ipv6 now.

**Comment by jaikishantulswani** [comment]
@leonjza Thank you for this prompt feature but the updated version is still not able to take screenshots of ips with ports like 
127.0.0.1:52
172.52.6.6:5263

**Comment by leonjza** [comment]
The two examples you posted now aren't valid URI's though, but I can update the parser to handle those as well, prefixing a scheme.

**Comment by jaikishantulswani** [comment]
@leonjza but the version i am using of gowitness: 2.5.1 is taking screenshot from these examples

**Comment by leonjza** [comment]
Yeah, it's definitely a regression.

**Comment by leonjza** [comment]
_Should_ now work as expected: https://github.com/sensepost/gowitness/commit/66eec626ab3bdb90c670eb1b63ac85f0302ccdb0. Also added a small test to help.

**Comment by jaikishantulswani** [comment]
@leonjza Can you let me know why I am not getting the screenshot, please let me know if I am doing anything wrong.

gowitness scan file -f c -t 15 -T 15 --screenshot-path ./screenshots --write-db --chrome-path /root/xfolder

my  file is like
127.0.0.1:8080
192.168.50.20:6054

**Comment by leonjza** [comment]
Sure you have the latest version? From a target parsing & generation perspective though, since my last commit it seems to work fine now (see the witnessing lines below).

```text
❯ cat c
127.0.0.1:8080
192.168.50.20:6054

❯ gowitness -D scan file -f c
2024/09/19 15:40:57 DEBU <cmd/root.go:28> debug logging enabled
2024/09/19 15:40:57 DEBU <cmd/scan.go:72> scanning driver started driver=chromedp
2024/09/19 15:40:57 WARN <cmd/scan.go:109> no writers have been configured. to persist probe results, add writers using --write-* flags
2024/09/19 15:40:57 DEBU <runner/runner.go:42> final screenshot path screenshot-path=<snip>/gowitness/screenshots
2024/09/19 15:40:57 DEBU <cmd/scan_file.go:57> starting file scanning file=c
2024/09/19 15:40:57 DEBU <drivers/chromedp.go:122> witnessing 👀 target=http://192.168.50.20:6054
2024/09/19 15:40:57 DEBU <drivers/chromedp.go:122> witnessing 👀 target=https://127.0.0.1:8080
2024/09/19 15:40:57 DEBU <drivers/chromedp.go:122> witnessing 👀 target=https://192.168.50.20:6054
2024/09/19 15:40:57 DEBU <drivers/chromedp.go:122> witnessing 👀 target=http://127.0.0.1:8080
2024/09/19 15:42:00 DEBU <drivers/chromedp.go:462> closing browser allocation context
```

If your targets are up, check that you have the latest version. How you installed will mean some of the `version` output may not show commit id info.

```
❯ build/gowitness-3.0.2-darwin-arm64 version
               _ _
 ___ ___ _ _ _|_| |_ __ ___ ___ ___
| . | . | | | | |  _|  | -_|_ -|_ -|
|_  |___|_____|_|_||_|_|___|___|___|
|___|    v3, with <3 by @leonjza

gowitness: 3.0.2
git hash: bbdccbe
build env: go1.23.1_linux/arm64
build time: 2024-09-19T13:29:39Z
```

**Comment by jaikishantulswani** [comment]
@leonjza Yes, I am using this 

./gowitness-3.0.2-linux-amd64 version                                                                          default@us-west-2
               _ _                   
 ___ ___ _ _ _|_| |_ __ ___ ___ ___ 
| . | . | | | | |  _|  | -_|_ -|_ -|
|_  |___|_____|_|_||_|_|___|___|___|
|___|    v3, with <3 by @leonjza

gowitness: 3.0.2
git hash: bbdccbe
build env: go1.23.1_linux/arm64
build time: 2024-09-19T13:29:39Z

**Comment by leonjza** [comment]
I'm sorry, I cannot replicate the original issue in the latest release anymore.

**Comment by jaikishantulswani** [comment]
@leonjza It works :) and sorry, my bad, there was some tabs (spaces) before the address in new file, thats why it was not working, but now it works fine :)

**Comment by leonjza** [comment]
Good call on the spaces! Added a check and test for that.
