### ISSUE TITLE
something wrong with stdin

### ISSUE THREAD

**Issue by kingjly** [sensepost/gowitness#233]
**Describe the bug**
When i run gowitenes to scan file from stdin like blow

`echo https://www.bing.com | gowitness.exe scan file -f - --write-db`   
or use type command to print urls from file like blow
`type .\xxx.txt | gowitness.exe scan file -f - --write-db`

it shows  An error occured running the  file  command  
The error was:  source is not readable

**Screenshots**
![image](https://github.com/user-attachments/assets/a85ec969-7fa9-4af7-ad41-a191b409ff09)

**Version Information:**
 - OS: Windows 11
 - gowitness: 3.0

**Comment by leonjza** [comment]
Thanks for the report. Should be fixed now!
