### ISSUE TITLE
Screenshots aren't loading properly

### ISSUE THREAD

**Issue by j1cs** [sensepost/gowitness#235]
**Describe the bug**
Usin `/api/submit/single` doesn't load the image

**To Reproduce**
Sending the following:
```
 {
   "options": {
      "window_x": 769,
      "window_y": 1024
   },
   "url": "https://x.com/Dexerto/status/1836865345627275363"
}
```
The log says `200`

```
2024/09/22 00:00:42 INFO result 🤖 target=https://x.com/Dexerto/status/1836865345627275363 status-code=200 title="" have-screenshot=true
2024/09/22 00:00:42 "POST http://localhost:7171/api/submit/single HTTP/1.0" from 172.18.0.17:41844 - 200 282397B in 3.77516472s

```

**Expected behavior**
The previous version `2.5.1` the screenshot worked fine.

**Screenshots**
![27717256-eb9f-4008-9ea6-d5b9cde602e0](https://github.com/user-attachments/assets/145bcc82-ba72-48f7-a354-0d87a983f7a4)

**Version Information:**
 - OS: Archlinux
 - gowitness: latest docker version

**Comment by leonjza** [comment]
I could replicate this when a delay is not set. It's set when using the command line to 3 seconds, but now I have also exposed it in the submission API endpoints: https://github.com/sensepost/gowitness/commit/1db81b3b4f3cf66b9806be4aa9d2bd4c0264f8e6

I've also added a new immediate mode probe UI to test it (along with the ability to tweak the delay). https://github.com/sensepost/gowitness/commit/bb5cf4fc2c3e11ff8255d9bb40ac9500aeba7303

<img width="1463" alt="image" src="https://github.com/user-attachments/assets/56e477a5-48ef-4eee-9785-41aead1bd0c6">

**Comment by j1cs** [comment]
I see. I’m not an expert, but since you use the developer tools protocol, wouldn’t it be better to know when the page is completely loaded?

**Comment by leonjza** [comment]
That is a surprisingly hard problem. Not all pages behave the same – some will have window.onload fire before its actually finished. It's so unpredictable that there are countless strategies to check if a page is "loaded". Eg, this [WaitDomStable](https://github.com/go-rod/rod/blob/0096e531a49c82f272f5661eabe755d2e7c1eb61/page.go#L783) function that waits for a period of time, checking if the DOM hasn't meaningfully changed for a duration.

In my testing, the delayed approach is generic and "good enough" having success with the majority of what you'll throw at it.
