### ISSUE TITLE
gowitness report list by default opens gowitness.sqlite3 in write mode

### ISSUE THREAD

**Issue by boozezela** [sensepost/gowitness#244]
Running `gowitness report list` automatically writes a `gowitness.sqlite3` database if this does not exist.

While it is understandable that gowitness tries to open `gowitness.sqlite3` by default, this should not be opened in write mode.

When `gowitness.sqlite3` is missing, it could be beneficial to output an error along the lines of _"Could not find gowitness.sqlite3. Use --db-uri <string> or --json-file <string> to specify a data source"_.

Alternatively, make either `--db-uri` or `--json-file` mandatory.

```
$ ls -l
total 0

$ gowitness report list
╭──────┬────────┬──────┬───────────┬───────┬───────┬─────┬─────┬────────┬────────╮
│ When │ Failed │ Code │ Input URL │ Title │ ~Size │ Net │ Con │ Header │ Cookie │
├──────┼────────┼──────┼───────────┼───────┼───────┼─────┼─────┼────────┼────────┤
╰──────┴────────┴──────┴───────────┴───────┴───────┴─────┴─────┴────────┴────────╯

$ ls -l
total 136
-rw-r--r--  1 user  staff  69632  3 Oct 11:54 gowitness.sqlite3

```

**Comment by leonjza** [comment]
Should be fixed now. Gosh that was annoying :D

**Comment by j1cs** [comment]
This change broke my current setup and i don't even use/care about the database. 
the program shouldn't create the sqlite3 file if doesn't exists?
i had:
```
  gowitness:
    image: ghcr.io/sensepost/gowitness:latest
    command: gowitness report server --host=0.0.0.0
```
gave me this error:
```
2024/10/10 21:34:58 ERRO could not get api handler up err="sqlite database file does not exist: gowitness.sqlite3"
```
i tried 
```
  gowitness:
    image: ghcr.io/sensepost/gowitness:latest
    command: gowitness report server --host=0.0.0.0 --db-uri sqlite://gowitness.sqlite3
```
i got
```
gowitness-1  | 2024/10/10 21:36:13 ERRO could not get api handler up err="sqlite database file does not exist: gowitness.sqlite3"
```

with this:
```
  gowitness:
    image: ghcr.io/sensepost/gowitness:latest
    command: gowitness report server --host=0.0.0.0 --db-uri /tmp/gowitness.sqlite3
```
i got:
```
2024/10/10 21:38:29 ERRO could not get api handler up err="invalid db uri scheme"
```

**Comment by leonjza** [comment]
@j1cs sorry about that, should be fixed now.

**Comment by j1cs** [comment]
Your dedication and quick response more than make up for everything else bro. Thanks a lot!
