### ISSUE TITLE
screenshots written to db dont show up in the reporting ui

### ISSUE THREAD

**Issue by leonjza** [sensepost/gowitness#246]
screenshots written to the database (using `--write-screenshots`), used by the reporting ui don't show up. instead, the ui is still expecting a file which wont be available here.

**Comment by arjun0x1c** [comment]
You may need to write that in the database using --write-db.

**Comment by leonjza** [comment]
The writer is set to db here already. The cause is the UI does not read the `.screenshot` property from the model.
