### ISSUE TITLE
 ERROR: could not unmarshal event: unknown ClientNavigationReason value: initialFrameNavigation

### ISSUE THREAD

**Issue by fuomag9** [sensepost/gowitness#247]
**Describe the bug**
2024/10/08 22:27:49 ERROR: could not unmarshal event: unknown ClientNavigationReason value: initialFrameNavigation

**Version Information:**
 - OS: kali linux, docker
 - gowitness: latest

**Additional context**
Seems to be related to #135

**Comment by leonjza** [comment]
there was a cdproto update which gowitness also has now. are you sure you have the latest container (`docker pull`)? my testing does not replicate this.

```
❯ docker run --rm -it leonjza/gowitness gowitness scan single -u https://sensepost.com --write-stdout
https://sensepost.com
2024/10/09 07:53:49 INFO result 🤖 target=https://sensepost.com status-code=200 title=":: Orange Cyberdefense ::" have-screenshot=true
❯ 
```
