### ISSUE TITLE
Add DOM dumping

### ISSUE THREAD

**Issue by leonjza** [sensepost/gowitness#25]
This can be added with the `-dump-dom` Chrome flag: https://developers.google.com/web/updates/2017/04/headless-chrome#printing_the_dom

**Comment by 424242424** [comment]
is this issue up for grabs?

**Comment by leonjza** [comment]
Absolutely. I just added it so that I don't forget, but PR's welcome!

My current thinking would be to add a new `DumpURLDom` method next to [`ScreenshotURL`](https://github.com/sensepost/gowitness/blob/bcc6a21244a3052589163131aa21e357abe53a9c/chrome/chrome.go#L146), extracting some of the duplicated code we would have out of the latter. Dumping the DOM should also maybe not be the default, so adding it as a flag would be good.
