### ISSUE TITLE
Screenshots - Add option to ignore/handle SSL certificate warning.

### ISSUE THREAD

**Issue by ScatteredThoughts** [sensepost/gowitness#250]
I've noticed that there URLs which do not have screenshots, despite there being a 200 status. I manually browsed to some of them and noticed they all were giving a error for a bad cert on the domain, and required me to explicitly tell my browser that I want to proceed. It appears that gowitness does not know how to handle this warning and does not take a screenshot at all.

Is it possible to add an option for gowitness to handle these warnings and continue, so that it can get a screenshot of the actual web page, in spite of the problems with the SSL certificate?

OS: Linux Mint 21.3
gowitness: 3.0.4, precompiled release

**Comment by leonjza** [comment]
Can you give some examples?

The chromedp driver should [ignore cert errors](https://github.com/sensepost/gowitness/blob/3.0.4/pkg/runner/drivers/chromedp.go#L74) as well as the gorod driver [should](https://github.com/sensepost/gowitness/blob/3.0.4/pkg/runner/drivers/go-rod.go#L96).

Some quick testing using https://badssl.com/ confirms this for me as well:

```console
❯ go run main.go scan single -u https://self-signed.badssl.com/
2024/10/12 20:59:13 WARN no writers have been configured. to persist probe results, add writers using --write-* flags
2024/10/12 20:59:18 INFO result 🤖 target=https://self-signed.badssl.com/ status-code=200 title=self-signed.badssl.com have-screenshot=true
```

```console
❯ go run main.go scan single -u https://wrong.host.badssl.com/
2024/10/12 21:01:30 WARN no writers have been configured. to persist probe results, add writers using --write-* flags
2024/10/12 21:01:34 INFO result 🤖 target=https://wrong.host.badssl.com/ status-code=200 title=wrong.host.badssl.com have-screenshot=true
```

```console
❯ go run main.go scan single -u https://expired.badssl.com/
2024/10/12 21:02:34 WARN no writers have been configured. to persist probe results, add writers using --write-* flags
2024/10/12 21:02:39 INFO result 🤖 target=https://expired.badssl.com/ status-code=200 title=expired.badssl.com have-screenshot=true
```

```console
❯ go run main.go scan single -u https://untrusted-root.badssl.com/
2024/10/12 21:02:59 WARN no writers have been configured. to persist probe results, add writers using --write-* flags
2024/10/12 21:03:03 INFO result 🤖 target=https://untrusted-root.badssl.com/ status-code=200 title=untrusted-root.badssl.com have-screenshot=true
```

```console
❯ go run main.go scan single -u https://revoked.badssl.com/
2024/10/12 21:03:55 WARN no writers have been configured. to persist probe results, add writers using --write-* flags
2024/10/12 21:04:00 INFO result 🤖 target=https://revoked.badssl.com/ status-code=200 title=revoked.badssl.com have-screenshot=true
```

**Comment by ScatteredThoughts** [comment]
Strange. I'm not able to reproduce it now. I'm wondering if it may be something with how Akamai is handling the request, even though the rate was relatively slow.

Sorry for the trouble. This can be closed.
