### ISSUE TITLE
Version 3 seems to not support lots of 2 functionality

### ISSUE THREAD

**Issue by skorokithakis** [sensepost/gowitness#254]
Hello,
I recently upgraded to version 3, and it seems like the application was entirely rewritten, and doesn't support functionality that version 2 did, is that correct? For example, I had a workflow that didn't write a DB, and that outputted a single screenshot to PNG with a given height and width, but I can't find any of those command-line options now.

Is it possible for version 3 to do something like the following command?:

`gowitness single -X 540 -Y 960 --disable-db -P . -o gowitness.png http://myurl`

If not, is the recommendation that I stick with version 2?

**Comment by leonjza** [comment]
Basically everything got ported. What you want to do is all possible apart from setting the final file name (can open a feature request for that). Best would be to add `--help` to the different sub commands to learn whats possible in v3.

That said, your ask in v3 looks something like this:

```
gowitness scan --chrome-window-x 540 --chrome-window-y 960 --screenshot-path . --write-none single --url https://sensepost.com
```

**Comment by skorokithakis** [comment]
Thank you, I checked `--help` but somehow skipped over `--chrome-window-x/y` (I was expecting `-X` or `--width` or similar). I'll open a feature request for the filename, thank you.
