### ISSUE TITLE
Unable to Display Screenshots in Gowitness Report Server Despite Successful Scan

### ISSUE THREAD

**Issue by krn966** [sensepost/gowitness#259]
I've scanned the files using the command gowitness scan file -f filename.txt, which successfully took screenshots and stored them in the ./screenshots directory. Everything seems to be in place, but when I try to start a server to view the screenshots with gowitness report server . or gowitness report server, no screenshots are displayed.

**Screenshots**
![Screenshot from 2024-10-27 00-47-10](https://github.com/user-attachments/assets/c1922347-83f2-4ebf-9d35-a4035b3e411d)

**Version Information:**
 - OS: NAME="Kali GNU/Linux"
          VERSION_ID="2024.3"
          VERSION="2024.3"
          VERSION_CODENAME=kali-rolling

 - gowitness: 3.0.5

**Comment by leonjza** [comment]
Did you enable the db writer with `--write-db`? If you didn't, gowitness would have written a warning line to tell you its going to take screenshots but not save any data.

**Comment by krn966** [comment]
@leonjza  Thanks for the clarification! It's working now. Since it was set as a default function in the previous version, I assumed it would be a default function here as well.
