### ISSUE TITLE
V2 to V3 default changes with --write-db

### ISSUE THREAD

**Issue by bandrel** [sensepost/gowitness#262]
By default in version 2 the scanning wrote to the DB. Now in version3 you need to specify `--write-db` in order for any of the reporting features to work. 

I think either a README message update describing the change between versions or a change so that --write-db is enabled by default and is disabled with a switch.

**Comment by leonjza** [comment]
We can add a note. When you have no writers enabled, a `WARN` is written stating that though.

**Comment by bandrel** [comment]
Yea i saw that warning and it didnt click for me at first. I wrote this so that if someone is googling for it they would find it.

**Comment by ZerkerEOD** [comment]
Same with me. I just ran a pretty large scope and the warn just pause to let you know "Hey this isn't going to write to the database at all, would you like to continue"
