### ISSUE TITLE
Relative path for report screenshots

### ISSUE THREAD

**Issue by ravenium** [sensepost/gowitness#29]
When I move a report/db/screenshots around it breaks screenshot viewing because the report screenshot urls are absolute path'ed.  This means I end up having to sed the leading path out.  Can we get an option to add relative paths for screenshots?

**Comment by ravenium** [comment]
When I move a report/db/screenshots around it breaks screenshot viewing because the report screenshot urls are absolute path'ed.  This means I end up having to sed the leading path out.  Can we get an option to add relative paths for screenshots?

**Comment by leonjza** [comment]
Ah thanks for the reminder. Yes, this is definitely something to fix.
