### ISSUE TITLE
Question: Issue with url not having the prefix http:// or https://

### ISSUE THREAD

**Issue by g33kyshivam** [sensepost/gowitness#31]
Hi! So when I supply list of urls which don't have the http:// or https:// . I'm getting this error ``Skipping Invalid URL `` so does gowitness automatically prefix urls with http:// or https:// as mentioned in this issue #11 or do we have to supply an additional argument?

The command which I used: gowitness file -s ~/Desktop/urls.txt

**Comment by leonjza** [comment]
Hey! You would need to add `--prefix-http` / `--prefix-https` (or both) depending on what you would like to happen.
