### ISSUE TITLE
Add example of file usage in the main documentation

### ISSUE THREAD

**Issue by acmello** [sensepost/gowitness#32]
Pretty simple stuff: I couldn't find examples for `file` flag when checking the docs. Also, the info presented when running --help doesn't say much. Ended up checking the `file.go` to get the proper syntax and then came across this: 

```
$ gowitness file -s ~/Desktop/urls
$ gowitness file --source ~/Desktop/urls --threads -2 
```

so maybe just add it directly to the main docs?

Thanks

**Comment by leonjza** [comment]
What extra information were you looking for? The quoted output you found in `file.go` is shown when you run the `--help` flag on the sub command.

```text
~ » gowitness file --help

Screenshot URLs sourced from a file. URLs in the source file should be
newline separated. Invalid URLs are simply logged and ignored.

For Example:

$ gowitness file -s ~/Desktop/urls
$ gowitness file --source ~/Desktop/urls --threads -2

Usage:
  gowitness file [flags]

...
```
