### ISSUE TITLE
User Agent flag does not change user agent

### ISSUE THREAD

**Issue by fuzzerk** [sensepost/gowitness#36]
Problem: User-Agent is always "Go-http-client/1.1" 

Expected behavior: According to the binary's help documentation, the default UA is supposed to be "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36", though, testing shows it is "Go-http-client/1.1" without using the --user-agent flag. Setting the --user-agent flag to something different , also results the same - "Go-http-client/1.1"

I noticed this due to many of the screenshots saying something along the lines of "prove you're not a bot".

Please let me know how to fix this, or if it is my mistake. Also, thank you for the excellent tool!

**Comment by leonjza** [comment]
Interesting. So requests within gowitness ultimately happen in two places. The first just probes the site using the gorequest http library, and the second is from Chrome. The Chrome User-Agent gets passed on [here](https://github.com/sensepost/gowitness/blob/1d0d1f574bc6f9f7599e7283311dd2b2c339b6a1/chrome/chrome.go#L149) and the gorequest User-Agent [here](https://github.com/sensepost/gowitness/blob/1d0d1f574bc6f9f7599e7283311dd2b2c339b6a1/utils/processor.go#L36), so I would not expect to see the golang default User-Agent anywhere.

Will definitely have to test this and see whats going on.
