### ISSUE TITLE
Is it possible to use chromium instead of chrome?

### ISSUE THREAD

**Issue by sxiii** [sensepost/gowitness#37]
Would it work?

**Comment by leonjza** [comment]
We search for common `chromium` locations [here](https://github.com/sensepost/gowitness/blob/1d0d1f574bc6f9f7599e7283311dd2b2c339b6a1/chrome/chrome.go#L55-L64), but you can also specify the path with the `--chrome-path` [flag](https://github.com/sensepost/gowitness/blob/2aa789a2cc3dd83514f6f8ef240326769eb133ff/cmd/root.go#L140).

**Comment by sxiii** [comment]
Oh cool tested with --chrome-path and it actually worked; thanks @leonjza
