### ISSUE TITLE
Feature request: default ports/protocols for a list of hosts and ips

### ISSUE THREAD

**Issue by Viss** [sensepost/gowitness#38]
It would be superb if gowitness was able to attempt screenshots for a list of default ports, on both http and https if given a text file (or stdin?) full of ips or hostnames. 
as it stands now, gowitness needs to be told what protocol (http or https) and what port, but with enough threads and a low timeout, making attempts to stuff that isnt open/up goes pretty fast, so having a list of like half a dozen default ports to try (80, 8080, 443, 4433, 8888, 81, 90 etc) and to try both http and https for each as "default functionality" would dramatically increase gowitnesses portability!

**Comment by leonjza** [comment]
Nice, thanks for the suggestion. Should be super simply to implement too!
