### ISSUE TITLE
report generation doesnt permit specifying destination dir/name

### ISSUE THREAD

**Issue by Viss** [sensepost/gowitness#39]
./gowitness report generate -D test.db -d /tmp/test/asdfasdf/

will generate an html report and put it in the current working directory, and not place the report in the designated dir based on the cmdline. this is problematic for automation when screenshotting multiple domains using a wrapper script. Also it appears you cant give the report a name other than 'report-0.html', which is also problematic if you're screenshotting several dozen or several hundred domains and each domain needs to have its own report.

**Comment by skluthe** [comment]
You want to use -f to specify the file to output.

**Comment by leonjza** [comment]
I just added logic to effectively disable chunking should one want a single report. Just set `-c 0`. With `-n` you can control the file name.
