### ISSUE TITLE
CC License

### ISSUE THREAD

**Issue by altf4** [sensepost/gowitness#4]
Great tool! 

Just a word about the license, though, Creative Commons isn't really meant to be used for software. They even explicitly recommend against it:

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

I'd love to make some changes / features / etc..., but things like the non-commercial clause of the CC license here make that problematic. 

Thanks!

**Comment by leonjza** [comment]
Hey,

Thanks for mentioning this! I have started an internal discussion about this. Out of curiosity (as a non-legal person), what exactly is preventing you from contributing? I am aware of the incompatibilities with CC and osftware etc, but am curious about the restrictions you are facing other than turning this into a commercial thing?

Thanks in advance!

**Comment by altf4** [comment]
The line between "commercial" and "non-commercial" is kind of nebulous. I'm a professional security analyst, for instance. If I make some changes to the project as a part of some research and use it for my work, is that "commercial"? Probably. Just because you're not selling it as a widget doesn't make it "non-commercial". A not-unreasonable interpretation of the CC-NC would prevent such a use.  (I have no interest in "selling" anything to do with gowitness)

What you're **probably** looking for here is a copyleft license like the GPL. It would require that any changes made to the program also be licensed under the GPL. Basically, it encourages open source usage and development, while preventing some company from bottling it up as a proprietary tool and keeping it to themselves.
