### ISSUE TITLE
Failed to query url

### ISSUE THREAD

**Issue by Ahsan-x** [sensepost/gowitness#42]
**Describe the bug**
Trying to screen shot single url

**To Reproduce**
1.Type this in terminel and get the following error 
gowitness single --url=https://www.facebook.com/
Error
gowitness single --url=https://www.facebook.com/
ERRO[2020-04-01 15:32:28] Failed to query url                           error="[context deadline exceeded (Client.Timeout or context cancellation while reading body)]" url="https://www.facebook.com/"
INFO[2020-04-01 15:32:28] Complete                                      run-time=3.1479092s
**Screenshots**
![image](https://user-images.githubusercontent.com/46222314/78127901-6c267a00-742e-11ea-8bf0-470978515819.png)

**Version Information:**
 Ubuntu WSL (Windows)

**Comment by leonjza** [comment]
Seems ok for me on macOS. I'll need help debugging WSL, it is not a platform I use. Maybe try a Linux VM instead?
![image](https://user-images.githubusercontent.com/1148127/78128365-0e863380-7416-11ea-8767-441dd58371a1.png)

**Comment by Ahsan-x** [comment]
@leonjza  thank you for your humble response. I will try it on vm

**Comment by d4rk-d4nph3** [comment]
@leonjza I am getting the same as @Ahsan-x on my Kali 2020.1.

**Comment by nicolas-gagnon** [comment]
I have a list of domain and sub domain I'm wondering if it's possible to query the list with no HTTPS:///

**Comment by sanjaypopcorn** [comment]
I have the same issue

**Comment by leonjza** [comment]
Any details? Without it a cannot debug anything.

**Comment by sanjaypopcorn** [comment]
> Any details? Without it a cannot debug anything.

Sorry here you go
![Screenshot from 2020-04-20 20-16-08](https://user-images.githubusercontent.com/42700088/79765683-8f18bf80-8344-11ea-972d-9a3f76d90ec8.png)

**Comment by smartgigs94** [comment]
Hi, 
I am facing an issue with gowitness. I am using WSL2 Kali 
![gowitness-error](https://user-images.githubusercontent.com/12003362/79975060-fdca5a00-84b7-11ea-99a2-d660f07c4635.png)

The command which I am running is 
![image](https://user-images.githubusercontent.com/12003362/79975132-1aff2880-84b8-11ea-8045-dcbecd0c58cd.png)

**Comment by leonjza** [comment]
`gowitness` uses Chrome itself, not the `chromedriver` component.

> I am facing an issue with gowitness. I am using WSL2 Kali

Unfortunately, I have never tested on WSL2 (and probably won't soon). PR's welcome to improve suport!

**Comment by smartgigs94** [comment]
If I remove --timeout=100, I get below error.
![image](https://user-images.githubusercontent.com/12003362/79976288-f2782e00-84b9-11ea-8797-14b63d99e0ba.png)

**Comment by smartgigs94** [comment]
> `gowitness` uses Chrome itself, not the `chromedriver` component.
> 
> > I am facing an issue with gowitness. I am using WSL2 Kali
> 
> Unfortunately, I have never tested on WSL2 (and probably won't soon). PR's welcome to improve suport!

Thanks for replying. I will try to use chrome and see if it works out

**Comment by leonjza** [comment]
I just landed https://github.com/sensepost/gowitness/commit/2699bf210e14b66f8fac43c4f1f9bebd1c1c8eea which will report the Chrome binary used for the screenshot. Running gowitness with the `--log-level debug` flag, you should see the full arguments used which you could in turn run manually. This should help rule out if this is Chrome having a problem, or gowitness.

Eg:

```
» gowitness --disable-db --log-level debug single -u https://facebook.com/

[...]

DEBU[2020-08-13 16:30:57] Google Chrome arguments                       arguments="[--headless --disable-gpu --hide-scrollbars --disable-crash-reporter --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36 --window-size=1440,900 --screenshot=https-facebook.com.png --virtual-time-budget=2000 --allow-insecure-localhost http://localhost:58265/]" binary="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
INFO[2020-08-13 16:30:57] Taking screenshot                             destination=https-facebook.com.png url="https://www.facebook.com/"

[...]

INFO[2020-08-13 16:30:59] Complete                                      run-time=5.480074946s
```

Taking the details from the `Google Chrome arguments` log entry, you can reconstruct the command gowitness ran as:

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --headless --disable-gpu --hide-scrollbars --disable-crash-reporter --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36" --window-size=1440,900 --screenshot=https-facebook.com.png --virtual-time-budget=2000
```

This should hopefully help in figuring out whats going on in the future.
