### ISSUE TITLE
Does not redirect to HTTPS

### ISSUE THREAD

**Issue by merati** [sensepost/gowitness#44]
I'm running the script using the file command, and have lots of URLs in my target file. The problem is when the URL is http://x.x.x.x and the response is a redirect to https://x.x.x.x, the script doesn't follow the redirect which results in lots of blank png files.

**Comment by leonjza** [comment]
You could preprocess your input files using something like [httpx](https://github.com/projectdiscovery/httpx) and then pipe the results to gowitness. For example: https://twitter.com/pdiscoveryio/status/1293918612722348034
