### ISSUE TITLE
Accept set-cookie to bypass waf's

### ISSUE THREAD

**Issue by httpnotonly** [sensepost/gowitness#45]
**Is your feature request related to a problem? Please describe.**
Lot's of WAF screenshots

**Describe the solution you'd like**
accept cookies to send

**Comment by leonjza** [comment]
Looking at the Chrome Headless command line switches, I don't think this is possible: https://source.chromium.org/chromium/chromium/src/+/master:headless/app/headless_shell_switches.cc

**Comment by jokaorgua** [comment]
@leonjza https://github.com/chromedp/examples/blob/master/cookie/main.go - here you can find an example of setting cookie. 

as for me this ticket could be re-opened
