### ISSUE TITLE
Nmap import scan all the ports

### ISSUE THREAD

**Issue by Stoo0rmq** [sensepost/gowitness#46]
Imagine we have an nmap output file that gave us which ports are opened and which ones are closed. gowitness instead of go only for the opens goes for every possible port therefore it does not make any distinction between open or closed ports.

The expected behaviour would be to only enumerate the open ports 

gowitness version: Latest, downloaded yesterday

Nmap command:
nmap -iL FILE -p80,8000 -T4 -oX OUTPUT --max-retries=2

Gowitness command:
gowitness nmap --nmap-file OUTPUT --threads 20

**Comment by leonjza** [comment]
#52 landed to address this.
