### ISSUE TITLE
Use firefox to take screenshot

### ISSUE THREAD

**Issue by dhra** [sensepost/gowitness#47]
I like to use firefox headless mode instead of chromium to taking screenshots. Firefox users can take screenshot using `--screenshot` flag via firefox binary. Check this resource to get more information:
[Take a screenshot from the command line with headless](https://bugzilla.mozilla.org/show_bug.cgi?id=1378010)

**Comment by leonjza** [comment]
I originally wanted to support this, but it was really resource intensive and the performance was extremely poor.
