### ISSUE TITLE
 error="open : no such file or directory"

### ISSUE THREAD

**Issue by mpgn** [sensepost/gowitness#48]
**Describe the bug**
No such file or directory while the file exist

**To Reproduce**
```
~/go/bin/gowitness file domain.txt                                                                                             10:22:42
FATA[2020-05-12 10:22:49] Unable to read source file                    error="open : no such file or directory" source=
```

**Expected behavior**
File to be read

**Version Information:**
 - OS: Linux
 - gowitness: latest version

**Comment by leonjza** [comment]
Check out `gowitness file --help`. To use a file, you need the `-s`/`--source` flag.

```
gowitness file -s domain.txt
```
