### ISSUE TITLE
Destination flags error compiling report

### ISSUE THREAD

**Issue by unl1k3ly** [sensepost/gowitness#5]
Hi,

Can't thank you enough for come up with this tool!

A last release, there's a but where when you specify screenshots folders and generate a report images does not reflect at db. As a result, screenshots won't load. 

I'm using --source flag with urls and -d ./screenshots/  flag. 

Cheers

**Comment by leonjza** [comment]
Thanks for the report! I'll look into this as soon as possible.

**Comment by leonjza** [comment]
Should be fixed in 1.0.6. Let me know!

**Comment by unl1k3ly** [comment]
Hi @leonjza, thanks for fixing it mate.

Although, wouldn't it be better to compile a report based on '-d' flag ?

Reason being is that when browsing from a web source, rather than a file:// it will always get the system path rather than './' location.

My suggestion would be to trust the '-d' flag as a valid screenshot location.

Like, '-d ./sreenshots' and compile it as ./sreenshots/http-xxxx:80.png' for example.

What you think of that ?

Cheers

**Comment by leonjza** [comment]
Ah yeah, good point, thanks!

**Comment by leonjza** [comment]
Think this has changed quite a bit since the original report. Feel free to open a new issue if something is still weird.
