### ISSUE TITLE
screenshot failed ，need help pls

### ISSUE THREAD

**Issue by a13202026257** [sensepost/gowitness#54]
Timeout reached while waiting for screenshot to finish  [31mdestination[0m=https-www.runoob.comechartsecharts-setup.html.png
...
command is  gowitness single --url=....com
version:windows10 
chrome-version:latest

**Comment by leonjza** [comment]
Check out [this comment](https://github.com/sensepost/gowitness/issues/42#issuecomment-673518577) to try and debug it.
