### ISSUE TITLE
Any Help

### ISSUE THREAD

**Issue by tibug** [sensepost/gowitness#56]
Screenshot failed !!!!

ERRO[2020-09-06 15:26:48] An error occurred while trying to get the Chrome version  chrome-path=/usr/bin/chromium-browser err="exit status 1"

![image](https://user-images.githubusercontent.com/68282195/92326740-93741980-f054-11ea-9a7d-18867c4cc635.png)

**Comment by leonjza** [comment]
While not complete yet, you can build from the current master which contains some major rework/refactorings for the upcoming v2 release and see if its better for you? If not, feel free to open another issue.
