### ISSUE TITLE
Display whois data in report

### ISSUE THREAD

**Issue by uBadRequest** [sensepost/gowitness#57]
**Is your feature request related to a problem? Please describe.**
When doing recon on domains containing specific words, i'm really interested in the registrant information. 

**Describe the solution you'd like**
Having a button in the report to view whois data. As well as a button to view the HTTP headers. Something like how Aquatone generates reports.

**Describe alternatives you've considered**
Trying to have a seperate process fetch whois data for all the domains and edit the report template to search for the corresponding whois data.

**Comment by leonjza** [comment]
Hey, unfortunately gowitness is not really the tool for that. The focus is specifically screenshotting websites, and doing that well. I am busy with a major refactor/cleanup for v2 which will also sport a fancy new report viewer. You can see a snippet of that here: https://twitter.com/leonjza/status/1305984759143837697
