### ISSUE TITLE
gowitness generate report.html breakdown 

### ISSUE THREAD

**Issue by unl1k3ly** [sensepost/gowitness#6]
I guess it would be a good idea to breakdown report.html into different html files rather than display it at a single file.

From time to time,  when scanning a large scope, the report.html becomes unresponsive due lack of memory (yeah! my laptop suck!).

So, I think this could be avoided by segmented report into, report.html, report_01.html, report_02.html etc. Maybe 20 screenshots in each file ?

I'll leave it up to you to decide! What you think of that idea ?

Once again, thanks a lot to come up with this awesome tool.

Cheers

**Comment by leonjza** [comment]
Yeah, the report definitely needs some clever chunking or a way to deliver it without making your system cry. Ideally, I should just start a small web server that will let you page/search through the results. Soon!

**Comment by unl1k3ly** [comment]
Thanks heaps mate! I legit should lean go so I can bother you less and do more pull requests! 
Thanks once again.
Cheers

**Comment by rootxharsh** [comment]
@leonjza I'm not it is possible or not but a report based on "domain" name will be better for example;
gowitness generate --domain=yahoo.com then it only generates report for *.yahoo.com, Will be a lot better.

**Comment by leonjza** [comment]
> @leonjza I'm not it is possible or not but a report based on "domain" name will be better for example;
> gowitness generate --domain=yahoo.com then it only generates report for *.yahoo.com, Will be a lot better.

Yeah I am planning some changes with the reporting components. Just need some time to sit down with it.

**Comment by rootxharsh** [comment]
Ah ok! Hoping to get that feature soon. I love this tool works really fine on my VPS.

**Comment by unl1k3ly** [comment]
@rootxharsh you can run on your vps as it is... create a folder called '/foot/bar' point nginx to that folder as well as gowitness. Problem solved !
