### ISSUE TITLE
Proxy Support Feature

### ISSUE THREAD

**Issue by randomactsofsecurity** [sensepost/gowitness#62]
**Describe the solution you'd like**
Add HTTP and SOCKS5 proxy support screenshot functionality

**Describe alternatives you've considered**
Related to the old issue https://github.com/sensepost/gowitness/pull/21

**Additional context**
Seems like chromedp has this built in support already, just need to stub in the options and test in chrome/chrome.go

https://github.com/chromedp/examples/pull/20/files/0bfcebe721cd401786649f72d0b7926369348623#diff-a5b9dfd3fa592c284ba488a7c748679e

**Comment by leonjza** [comment]
I played with this a bit last night actually and was having trouble getting a proxy configuration to work for Chrome. Maybe someone else could test it as well?

**Comment by randomactsofsecurity** [comment]
the chromedp proxyserver works fine, it's actually the preflight http.client that will need proxy support added as well.

I've got a local copy working with socks5, just need to allow it to work with http. Will make a PR soon

**Comment by randomactsofsecurity** [comment]
Added proxy support at PR #65 

I've tested without proxy, with a socks 5 and with a HTTP proxy and it seems to work for me. Should be good with a bit more validation on your part. I've also made it so it follows the global timeout argument, in case someone needs to delay the connection more

**Comment by randomactsofsecurity** [comment]
closed, merged in https://github.com/sensepost/gowitness/commit/9736345601bcb75f56ac5340b738d5615178eeb3
