### ISSUE TITLE
Export Urls based on status code

### ISSUE THREAD

**Issue by jaikishantulswani** [sensepost/gowitness#63]
Hi @leonjza Its not an issue but a request to have a feature for importing url's based on particular status code via the report viewer. Like a feature to filter screenshots based on status code and then export the urls to a text file.
Also have an option to increase number of screenshot per page and next button on the top too.

Regards,

**Comment by leonjza** [comment]
hey. for now you can use the `report list` command with the json output (`-j`) flag. use it in combination with [jq](https://stedolan.github.io/jq/) and you should have some pretty great report filtering capabilities.

**Comment by leonjza** [comment]
To be a little more verbose in my answer, here is how you could filter URL's in the report that had an HTTP 200.

```bash
gowitness report list -j | jq -r ". | select(.response_code==200) | .final_url"
```

As for the per_page value in the interactive report viewer, you can just manually modify the query string parameter for now.

**Comment by jaikishantulswani** [comment]
@leonjza thank you :+1:

**Comment by 0xtavian** [comment]
@leonjza Getting `error="unknown shorthand flag: 'j' in -j` when running `gowitness report list -j`. Updated to latest binary and still the same. Does `--log-format = json` need to be set at runtime? I couldnt find a mention of `-j` in the help menu.

**Comment by leonjza** [comment]
Instead of implementing complex filtering logic in gowitness, I've opted to just document the above `jq` example for those that may need that.
