### ISSUE TITLE
How to Access URL Behind Login?

### ISSUE THREAD

**Issue by frakman1** [sensepost/gowitness#64]
I don't see a way to use this on a website that has a login page. Is there a way to provide login credentials to this utility?

**Comment by leonjza** [comment]
While gowitness probably wont extend into the realm of automating actions, we can definitely add cookie/header append support so that you can use an existing session as an argument.

**Comment by frakman1** [comment]
Great. Looking forward to trying this out.

**Comment by ruevaughn** [comment]
I would also be very interested in this feature. If I were to implement this feature and open a PR, any insight on which parts fo the code I would start looking at?

**Comment by leonjza** [comment]
@ruevaughn off the top of my head, 2 places.

First, the light probing logic (a sort of preflight) [here](https://github.com/sensepost/gowitness/blob/2.3.6/chrome/chrome.go#L38). Second, in the chromedp invocation [here](https://github.com/sensepost/gowitness/blob/2.3.6/chrome/chrome.go#L130).

I think the harder of the two will be the chromedp integration as the API is not as obvious as that of `http.Client`.

Options parsing should use the same flow as others, handled [here](https://github.com/sensepost/gowitness/blob/master/lib/options.go).

**Comment by ruevaughn** [comment]
Awesome. When I get some time I am going to look at implementing this

**Comment by leonjza** [comment]
This landed in #124
