### ISSUE TITLE
Support for chromium

### ISSUE THREAD

**Issue by JDRanpariya** [sensepost/gowitness#68]
**Is your feature request related to a problem? Please describe.**
I'm miss some screenshots with chrome headless

**Describe the solution you'd like**
I would like if chromium is available for screenshotting the sites.

**Describe alternatives you've considered**
Chromium

**Additional context**
I hope it will be in actions ASAP.

**Comment by leonjza** [comment]
Im sorry but it is really hard to understand this one. We already use Chrome for screenshots. As for weirdness around screenshots there are a lot of factors, including your network connection and the remote web servers behavior. Without debugging that first it is impossible to do anything.

**Comment by leonjza** [comment]
If you want to use a specific version/build of Chrome/Chromium, you can use the chrome path flag.

**Comment by JDRanpariya** [comment]
Ok cool. I also want to ask about screenshotting of sites which do not have valid ssl  certificate generally chrome ignores the empty/blank pages. do you have any idea on how to screenshot such pages? ( phantomjs supports screenshotting sites without valid ssl certificate)

**Comment by leonjza** [comment]
gowitness should screenshot sites with invalid certificates just fine. I tested with all of the badssl.com subdomains successfully.

**Comment by JDRanpariya** [comment]
Then I think might be it's my network or server issue. I would like to close the issue but before that can you tell how does gowitness handles the redirects?

**Comment by leonjza** [comment]
It follows them.
