### ISSUE TITLE
Screenshot timeout (handling alert())

### ISSUE THREAD

**Issue by JoshuaMart** [sensepost/gowitness#71]
Hello,
Thanks for your tools, the new features are very interesting. However, I encounter a problem, it sometimes happens that the screenshot capture remains blocked (for example on a site that displays a popup like alertbox).

If GoWitness is launched in a script, the execution of the script is blocked.

Is it possible to add a default timeout or to be able to set this option?

Thank's,
Jomar

**Comment by leonjza** [comment]
Looks like there is a way to handle alert's as described [here](https://github.com/chromedp/chromedp/issues/574). We could implement `HandleJavaScriptDialog` as shown [here](https://github.com/chromedp/chromedp/blob/81aeb2a774604e64c3598b1c79fbd7182f8371aa/example_test.go#L327).

**Comment by JoshuaMart** [comment]
Seem's ok, thank's @Serizao
