### ISSUE TITLE
URL Watermarks

### ISSUE THREAD

**Issue by jtesta** [sensepost/gowitness#75]
**Is your feature request related to a problem? Please describe.**
A feature to add a watermark to the image would make reporting much easier.  For example, if the images were imported into a Word document, the filename containing the URL is no longer visible.  Having the URL in the image itself would save time having to organize and include notes manually.

**Describe the solution you'd like**
One idea is to have a semi-transparent watermark in the corner.  That would look great, but might not show up well with certain backgrounds & website content.  An easier path would be to slightly extend the image's height and insert the URL at the top (essentially where a real browser's URL bar would go).

**Describe alternatives you've considered**
At this point, I'd have to manually insert images into a report, and re-type the URL each time.  This doesn't scale well with many images.

**Additional context**
N/A

Also, I'd like to say: great work on this tool!

**Comment by leonjza** [comment]
I played around with some implementations for this and couldn't really find anything that was slick enough for me. Happy for someone in the future to PR an implementation though,
