### ISSUE TITLE
Expose over internet not only localhost

### ISSUE THREAD

**Issue by nine9-nine9** [sensepost/gowitness#79]
It would be great to view my screenshots from a VPS when i run `gowitness report serve`.

**Comment by leonjza** [comment]
You can do this using the `--address ` / `-a` [flag](https://github.com/sensepost/gowitness/blob/2.2.0/cmd/report_serve.go#L67) (`--help` would have revealed that), setting it to something like `0.0.0.0:7171`. Keep in mind the interface has **no** authentication.
