### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by sl4cky** [sensepost/gowitness#8]
Hi, I get this error message while running the script on a url file list. 

FATA[2018-04-21 17:10:18] fork/exec /usr/bin/chromium: too many open files

**Comment by leonjza** [comment]
Hey,

What are all of the flags you are using to run `gowitness` as well as the output of `ulimit -n` ?

**Comment by sl4cky** [comment]
unlimit -n = 1024
gowitness flags: file --source <file>

**Comment by leonjza** [comment]
I have no idea why this happening. Does it happen immediately or after some time? Have you tried running it with `--threads 1`? Anything weird about your environment?

**Comment by sl4cky** [comment]
Well, I tried running it with the default threads and my environment is a Kali linux.

**Comment by leonjza** [comment]
Ok can you try it with `--threads 1`?

**Comment by sl4cky** [comment]
Hey, I will try
