### ISSUE TITLE
module declares its path as: github.com/chromedp/sysutil

### ISSUE THREAD

**Issue by StillNoob** [sensepost/gowitness#82]
I was trying to install gowitness using the following command:

`go get -u github.com/sensepost/gowitness`

I got the following output.

![Screenshot_2020-11-15_19-04-09](https://user-images.githubusercontent.com/65060964/99193513-7ab86c00-2747-11eb-8a25-7f63d97825e8.png)

Please reply, how can I fix this?

**Comment by leonjza** [comment]
I suspect you may have something else in your gopath that wants a different version of that dependency. I just did a fresh go get in a Kali VM, as well as rebuilt the docker container and both seem fine. The only thing I can suggest is to wipe out your go modules and try from fresh.
