### ISSUE TITLE
fails on ULRS with hash in it

### ISSUE THREAD

**Issue by joe-getcouragenow** [sensepost/gowitness#84]
https://gallery.flutter.dev/#/reply

```
gowitness --fullpage single https://gallery.flutter.dev/#/reply
04 Dec 2020 10:41:57 WRN preflight result statuscode=404 title="Page Not Found" url=https://gallery.flutter.dev/%23/reply

```

**Comment by leonjza** [comment]
While I fixed the hash parsing now, unfortunately that URL does not screenshot well with the JavaScript its using. I am not really sure why yet and am spread a bit thin to debug it now.

**Comment by joe-getcouragenow** [comment]
I worked out how to make it work.. Add a delay. I don't knwo why that fixes it. Could be a Flutter thing

But maybe this helps determine whats happening...
