### ISSUE TITLE
Add delay between the opening of the navigator and taking the screenshot

### ISSUE THREAD

**Issue by mpgn** [sensepost/gowitness#85]
Hello

I maybe wrong but I didn't find a way to add a delay between the opening of the navigator and taking the screenshot.

![image](https://user-images.githubusercontent.com/5891788/101655244-ad513e00-3a41-11eb-9a47-8bae7e357a18.png)

Lot of the time the screenshot is made too soon and the page is not fully loaded yet. I use eyeswitness with the delay option as a workaround currently

![image](https://user-images.githubusercontent.com/5891788/101654197-83e3e280-3a40-11eb-8d73-0dc19f388ad1.png)

Could be a nice addition.

**Comment by leonjza** [comment]
Yeah this makes sense, I'd have to double check how to do that using chromedp first.

**Comment by leonjza** [comment]
Heh, looks simple enough! https://github.com/chromedp/chromedp/blob/v0.5.4/chromedp.go#L629

**Comment by leonjza** [comment]
`gowitness --disable-db single https://www.twitter.com` actually results in a valid screenshot since this commit now. hah!

**Comment by mpgn** [comment]
Nice, thank you !!!

**Comment by mhmh55516** [comment]
Delay not works well.
![image](https://user-images.githubusercontent.com/28407784/176562982-4f9f3e58-2c12-4d65-8be1-2f2a09ca044d.png)
