### ISSUE TITLE
video

### ISSUE THREAD

**Issue by joe-getcouragenow** [sensepost/gowitness#86]
Is capturing video, instead of just stills, something of interest to people ?

**Comment by leonjza** [comment]
This is not something I have needed, but curious about the use case and example code for sure.

**Comment by joe-getcouragenow** [comment]
Well we are using gowitness in CI to capture screen shots of the app for the docs.
and we also want to do the same with video of the app.

**Comment by leonjza** [comment]
Unless a pull request arrives, I unfortunately won't be adding this anytime soon.
