### ISSUE TITLE
Installation fails on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by muehlburger** [sensepost/gowitness#88]
**Describe the bug**

Installation fails on Ubuntu 20.04.1.

**To Reproduce**

```
go version
go version go1.16 linux/amd64

go get -u github.com/sensepost/gowitness
go get: github.com/knq/sysutil@v0.0.0-20191005231841-15668db23d08 updating to
	github.com/knq/sysutil@v1.0.0: parsing go.mod:
	module declares its path as: github.com/chromedp/sysutil
	        but was required as: github.com/knq/sysutil
```

**Expected behavior**
Installation should successfully complete.

**Version Information:**
 - OS: Ubuntu 20.04.1

**Comment by leonjza** [comment]
I can replicate this, and I think we're due a dependency upgrade anyways. For now you can download the precompiled releases (or use the docker container).

**Comment by leonjza** [comment]
Should build fine from the latest commit now. Make sure to run `go clean` first. I'll publish another release shortly as well.
