### ISSUE TITLE
Public Key Algorithm field missed

### ISSUE THREAD

**Issue by fastfire** [sensepost/gowitness#91]
In a previous version of Gowitness it was possible to recover the field "Public Key Algorithm". The Public Key Algorithm refers to the public key inside the certificate. This certificate is used together with the matching private key to prove the identity of the peer (authentication).
In the current versione of Gowitness is possibile to recover, from tls_certificates table, the fields Signature Algorithm, Certification Authority Name and Common Name.
Is it possible to add the Public Key Algorithm field again? Thank you!

**Comment by leonjza** [comment]
Definitely, looks like I missed it when porting the database stuff to sqlite in v2. [ref](https://github.com/sensepost/gowitness/blob/1.x/utils/processor.go#L84)

**Comment by leonjza** [comment]
I just added this in https://github.com/sensepost/gowitness/commit/0f9d120a1e7fd17e1d6661a5f189d16d9f9f9540.

![image](https://user-images.githubusercontent.com/1148127/110437687-4f72d780-80be-11eb-946d-f68b24cb33c7.png)
