### ISSUE TITLE
Port selection option on report serve

### ISSUE THREAD

**Issue by mcsJDF01** [sensepost/gowitness#92]
I am running Gowitness in Windows to serve reports only, port 7171 is reserved on my machine I think because I have WSL2 installed.

I can't seem to tell Gowitness to use a different port for the report. Is this something that could be added?

**Comment by leonjza** [comment]
You can set it with the `--address` / `-a` flag on the `report serve` subcommand. The default is `localhost:7171` (as you'd see when you add `-h` to the command), but say you wanted to use port 80, set it with `-a "localhost:80"`
