### ISSUE TITLE
Functionality to Diff Between Two Reports

### ISSUE THREAD

**Issue by Greenwolf** [sensepost/gowitness#97]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to run gowitness once a week, and filter/diff only sites where the screenshot is different from the previous report. It would greatly help speed things up when looking at 1000s of sites.

**Describe the solution you'd like**
A button in the web interface to filter/diff/sort by changes based on a previous report

**Describe alternatives you've considered**
I've implemented some image comparison before in Python, but I don't have the go skills to implement this as a pull request. This is the link I used in Python which you might find helpful for image comparison.
https://www.pyimagesearch.com/2014/09/15/python-compare-two-images/

**Comment by leonjza** [comment]
This would need some change over time tracking as a core feature, and not something im planning right now. Maybe in the future.
