### ISSUE TITLE
[Question] ARM64 build??

### ISSUE THREAD

**Issue by gprime31** [sensepost/gowitness#99]
Any binary for arm64?  can't seem to build from source for arm64.

**Comment by leonjza** [comment]
What is the problem building from source?

**Comment by gprime31** [comment]
HI, I tried it again this morning, works fine now, yesterday it threw a file exec error for some reason, I used go get -u github.com/sensepost/gowitness both times...wierd.
Great tool 
Thanks for the fast response.
closing...
